import test from 'node:test';
import assert from 'node:assert/strict';
import { snapshot, comparison, sharedAt, axis, restoreReference, requestGate } from './thermal-comparison.mjs';
const config={rpm:3000,map_kpa:180,ambient_c:42,spark:8,lam:.92,fan:1,pump:1,heat_s:120,cool_s:90};
const result={frames:[{time_s:0,t_block:315.15,t_oil:315.15,t_turb:315.15}],method:'source dt=.1',initial_state:'cold_start_at_ambient'};
test('frozen request/result and deterministic restore',()=>{const run=snapshot(config,result);config.fan=.2;result.frames[0].t_block=999;assert.equal(run.request.fan,1);assert.equal(run.frames[0].t_block,315.15);assert.ok(Object.isFrozen(run.frames[0]));const restored=restoreReference(run);assert.equal(restored.run,run);assert.deepEqual(restored.draft,run.request);restored.draft.fan=0;assert.equal(run.request.fan,1);});
test('only actuators differ; durations/method/initial state invalidate',()=>{const a=snapshot({...config,fan:1},result);const b=snapshot({...a.request,fan:0,pump:.3},result);assert.deepEqual(comparison(a,b).changed,['fan','pump']);assert.equal(comparison(a,b).valid,true);for(const change of [{heat_s:30},{cool_s:60},{rpm:2500}])assert.equal(comparison(a,snapshot({...a.request,...change},result)).valid,false);assert.equal(comparison(a,snapshot(a.request,{...result,method:'other'})).valid,false);assert.equal(comparison(a,snapshot(a.request,{...result,initial_state:'warm'})).valid,false);});
test('exact timestamps, finite missing and signed/zero deltas',()=>{const a=[{time_s:0,t_oil:273.15},{time_s:2,t_oil:280}];const b=[{time_s:1,t_oil:300},{time_s:2,t_oil:278}];assert.equal(sharedAt(a,b,1),null);assert.equal(sharedAt(a,b,2).values.t_oil.delta,-2);assert.equal(sharedAt(a,a,0).values.t_oil.delta,0);assert.equal(sharedAt([{time_s:0,t_oil:null}],a,0).values.t_oil.delta,null);assert.equal(sharedAt([{time_s:0,t_oil:Infinity}],a,0).values.t_oil.reference,null);});
test('shared node axes include both runs, common elapsed axis and flat padding',()=>{const a=[{time_s:0,t_oil:273.15},{time_s:2,t_oil:280}];const b=[{time_s:4,t_oil:300}];const scales=axis(a,b,'t_oil');assert.equal(scales.timeMax,4);assert.ok(scales.min<=0&&scales.max>=26.85);const flat=axis(a.slice(0,1),[],'t_oil');assert.ok(flat.max>flat.min);});
test('async generation ignores superseded/unmounted requests',()=>{const gate=requestGate();const a=gate.begin(),b=gate.begin();assert.equal(gate.accept(a),false);assert.equal(gate.accept(b),true);gate.cancel();assert.equal(gate.accept(b),false);});

test('initial source temperatures must match even with equal metadata',()=>{const a=snapshot(config,result);const b=snapshot(config,{...result,frames:[{...result.frames[0],t_oil:999}]});assert.equal(comparison(a,b).valid,false);assert.ok(comparison(a,b).invalid.includes('initial_frame'));});
