/** Explicit Arabic/English presentation copy. Scientific identifiers and values stay literal. */
export const UI_COPY = Object.freeze({
  "المختبر ثلاثي الأبعاد": "3D studio",
  "جولة إرشادية": "Guided tour",
  "تجربة عملية": "Sandbox",
  "من السبب إلى الشيفرة": "Cause to code",
  "تدريب المناقشة": "Viva practice",
  "السيارة ومسار الهواء": "Vehicle and airflow",
  "المحرك والدورة": "Engine and cycle",
  "التيربو مكبّر": "Turbo detail",
  "الحرارة والتبريد": "Heat and cooling",
  "رؤية الطريق والقرار": "Road preview and decision",
  "الاستجابة المباشرة": "Live response",
  "أساسيات المحرك": "Engine fundamentals",
  "الذاكرة الحرارية": "Thermal memory",
  "مقارنة الاستباق": "Preview comparison",
  "إعادة تشغيل قيادة مسجلة": "Recorded drive replay",
  "مختبر سوبرا": "Supra Lab",
  "جارٍ قراءة فيزياء المشروع ونظام التحكم ومصادره…": "Loading project physics, controls and sources…",
  "إعادة الاتصال": "Reconnect",
  "سوبرا": "Supra",
  "/ مختبر": "/ Lab",
  "مشروعك، بكل تفاصيله.": "Your project, in detail.",
  "B58 بست أسطوانات متتالية": "B58 inline-six",
  "توجد مشكلة": "Connection issue",
  "المحاكاة المحلية متصلة": "Local simulation connected",
  "محاكاة فقط": "Simulation only",
  "أنماط التعلّم": "Learning modes",
  "النتائج البحثية": "Research results",
  "إخفاء الخطأ": "Dismiss error",
  "ابدأ من هنا": "Start here",
  "من الطريق إلى القرار.": "From road to decision.",
  "فكرة واحدة، وتجربة واحدة، ثم اربط الجزء التالي.": "One idea, one experiment, then connect the next part.",
  "الدرس الحالي": "Current lesson",
  "خارطة الدروس كاملة": "Full lesson map",
  "استكشف المشروع": "Explore the project",
  "اشرح الفكرة بثقة.": "Explain the idea with confidence.",
  "اتبع فضولك.": "Follow your curiosity.",
  "ابحث في المتغيرات": "Search variables",
  "RPM، لامدا، t_turb…": "RPM, lambda, t_turb…",
  "لا توجد متغيرات مطابقة.": "No matching variables.",
  "الأدلة ظاهرة دائمًا.": "Evidence always visible.",
  "هندسة مفاهيمية · وحسابات المشروع الفعلية": "Conceptual engineering · actual project calculations",
  "مختبر ميكانيكي · B58 / INLINE SIX": "Mechanical lab · B58 / INLINE SIX",
  "التعلّم بالتجربة": "Learn by experimenting",
  "سبب ← أثر ← مصدر": "Cause → effect → source",
  "التدرّب على المناقشة": "Viva practice",
  "من الهواء إلى قرار المشرف.": "From air to the supervisor decision.",
  "كيف يستفيد المشرف من الطريق القادم؟": "How does the supervisor use the road ahead?",
  "افحص التيربو داخل المنظومة.": "Inspect the turbo within the system.",
  "تتبّع الحرارة بين العقد.": "Track heat between the nodes.",
  "افتح المحرك. افهم الآلية.": "Open the engine. Understand the mechanism.",
  "غيّر متغيرًا، ثم راقب ما يتبعه.": "Change one variable, then observe the response.",
  "لكل جزء مسار يصل إلى الشيفرة.": "Every part has a path to the code.",
  "هل تستطيع شرح ما سيحدث؟": "Can you explain what will happen?",
  "إعادة ضبط المحاكاة": "Reset simulation",
  "مساحة التجارب": "Experiment workspace",
  "مطلع / معاينة متاحة": "Sighted / preview available",
  "أعمى / بلا معاينة": "Blind / no preview",
  "بُني حول مشروع تخرجك المحلي.": "Built around your local graduation project.",
  "مقاس فعليًا ≠ مستخرج من البيانات ≠ محاكاة ≠ افتراض.": "Measured ≠ derived ≠ simulated ≠ assumed.",
  "الأدلة والمراجع": "Evidence and references",
  "من يحسب هذا؟": "Who computes this?",
  "توضيح تعليمي لترتيب حساب المصدر، وليس تتبع تنفيذ غير متزامن. يستخدم عينة القصة الحالية.": "Teaching highlight of source computation order, not an asynchronous execution trace. Uses the current story sample.",
  "افحص مصدر هذه المسؤولية": "Inspect this responsibility in source",
  "التشغيل الحالي يعيد استعمال أوزان SAC جاهزة ومجمّدة. التدريب مسار منفصل يحدّث أوزان السياسة من الانتقالات والمكافأة؛ لا يوجد تدريب حي هنا.": "This run reuses frozen SAC weights. Training separately updates policy weights from transitions and reward; no live training occurs here.",
  "الوحدة الحالية أوامر يدوية؛ المسودة ليست خرج SAC متعلمًا.": "The current controller uses manual commands; the draft is not a learned SAC output.",
  "الوحدة الحالية سياسة مكتوبة يدويًا، وليست وكيل SAC متعلمًا.": "The current controller is a hand-written policy, not a learned SAC agent.",
  "مسار التدريب منفصل: يحدث أوزان SAC من الانتقالات والمكافأة. إعادة التشغيل تستخدم أوزان جاهزة ولا تدربها.": "Training is a separate path: it updates SAC weights from transitions and reward. Replay uses prepared weights without training them.",
  "مصدر التدريب": "Training source",
  "لماذا RL بدل توقع الحرارة فقط؟": "Why RL rather than only forecasting temperature?",
  "هذه قرارات متتابعة يتغير أثرها مع الحالة والذاكرة الحرارية والمكافأة المتراكمة. توقع الحرارة يجيب عن سؤال تنبؤ ويمكن أن يدخل متحكمًا؛ التنبؤ وحده لا يختار الفعل. MPC وتقليد سياسة معلّمة بدائل، ولا ندعي أن RL ضروري أو أفضل بلا مقارنة.": "These are sequential decisions whose effects depend on state, thermal memory and cumulative reward. A temperature predictor answers a forecasting question and can form part of a controller; prediction alone does not choose an action. MPC and imitation of a labelled policy are alternatives. We do not claim RL is necessary or better without a comparison.",
  "أساس حلقة الوكيل والمكافأة المتراكمة": "Agent loop and cumulative reward foundation",
  "أسئلة المناقشة": "Viva questions",
  "افتح المرحلة والمصدر": "Open stage and source",
  "غير متاح": "Unavailable",
  "طلب الفترة": "Interval torque demand",
  "العزم المتحقق / المرجع": "Delivered / reference torque",
  "خطأ التتبع: المتحقق − الطلب": "Tracking error: delivered − demand",
  "تدفق الوقود / المرجع": "Fuel flow / reference",
  "معدل مؤشر الضرر / المرجع": "Damage index rate / reference",
  "هل حقق القرار هدفه؟": "Did the decision meet its objective?",
  "العينة نفسها من الجلسة": "Same sample from session",
  "أزرار هذه البطاقة تفتح المصدر فقط؛ القراءات المعروضة تخص جلسة هذا المسار ولا تُرسل إلى مفتش المسار الآخر.": "Buttons in this card open source only; displayed readings belong to this lane session and are not sent to the other lane Inspector.",
  "افحص المصدر": "Inspect source",
  "خطأ نسبي ومقامه طلب الفترة": "Relative error; denominator is interval demand",
  "تكامل هذه الفترة = المعدل × زمن الخطوة": "This interval integral = rate × step duration",
  "تراكم الضرر / المرجع منذ بداية الجلسة": "Cumulative damage / reference since session start",
  "تراكم الوقود / المرجع": "Cumulative fuel / reference",
  "خفض تدفق الوقود؛ مقامه تدفق المرجع": "Fuel flow reduction; denominator is reference flow",
  "خفض تراكم الضرر؛ مقامه تراكم المرجع": "Cumulative damage reduction; denominator is reference total",
  "الصفر والسالب نتائج فعلية. لا يُحسب خفض بمقام مفقود أو غير موجب. انخفاض الوقود أو الضرر يُقرأ بجوار تلبية طلب العزم؛ قد لا يتحسن هذا المثال، ولا يثبت أمثلية عالمية.": "Zero and negative values are actual results. A missing or nonpositive denominator prevents a reduction calculation. Read fuel and damage alongside torque delivery; this example may show no improvement and does not prove global optimality.",
  "كيف حسبنا التقييم؟": "How was the evaluation computed?",
  "الأوزان المستخدمة فعلًا من ملاحظة الدخل": "Actual weights from input observation",
  "تفصيل مكتمل": "Complete decomposition",
  "تفصيل جزئي: عقوبتا عدم اليقين والنعومة غير مُصدّرتين": "Partial decomposition: uncertainty and smoothness penalties are not exported",
  "المجموع الموزون المتاح": "Available weighted subtotal",
  "عقوبة عدم اليقين / النعومة": "Uncertainty / smoothness penalty",
  "المكافأة الكلية المصدّرة": "Exported total reward",
  "المجموع هو مكافأة المصدر": "Total is source reward",
  "تكاليف العزم والطرق وEGT تشخيصات؛ لا تُخصم مرة ثانية. المكافأة تصميم من مقادير البيئة والمرجع وتفضيلات الهدف، وليست label لأفضل فعل ولا حساسًا مستقلًا للتحقق.": "Torque, knock and EGT costs are diagnostics; do not subtract them again. Reward is designed from environment quantities, reference and objective preferences; it is neither a label for the best action nor an independent validation sensor.",
  "معدل الضرر يجمع أسّيات حرارة التوربين والزيت وحد الطرق الاختياري. المؤشر نسبي/ثانية؛ تراكمه مجموع المعدل × dt. خفض 12% لا يعني زيادة العمر 12%، وفرق نقطتين مئويتين ليس نسبة خفض جديدة.": "Damage rate combines exponential turbine and oil temperatures with optional knock. It is a relative index per second; accumulation sums rate × dt. A 12% reduction does not mean 12% longer life; a difference in percentage points is not a new reduction percentage.",
  "افحص مصدر معدل الضرر": "Inspect damage rate source",
  "افحص مصدر المكافأة": "Inspect reward source",
  "مدخل السيناريو · زمن الدخل": "Scenario input · input time",
  "اللغة": "Language",
  "لغة الواجهة": "Interface language",
  "تبديل المظهر": "Toggle theme",
  "مظهر فاتح": "Light theme",
  "مظهر داكن": "Dark theme",
  "الجو الخارجي": "External atmosphere",
  "الضاغط / المبرد": "Compressor / intercooler",
  "قبل الخانق": "Before throttle",
  "مجمع السحب بعد الخانق": "Manifold after throttle",
  "مدخل السيناريو p_baro من الخانة 10 عند زمن دخل القرار. يمر إلى كثافة الجو ثم Vehicle.demand لطلب الطريق. مولدات الطريق تثبته عند 101.3؛ الارتفاع غير محاكى.": "Scenario p_baro from slot 10 at decision input time. It feeds ambient density and then Vehicle.demand for road demand. Road generators fix it at 101.3; altitude is not modeled.",
  "لا توجد قراءة ضغط لهذه المحطة. استدعاء سقف الضاغط في البيئة لا يمرر p_baro؛ يستخدم وسيط ضغط المدخل الافتراضي 99.3 kPa. هذا ثابت الدالة وليس قياسًا لهذه المحطة.": "No pressure reading is available at this station. The environment compressor-ceiling call does not pass p_baro; it uses the default inlet-pressure parameter of 99.3 kPa. This is a function default, not a station measurement.",
  "قناتا الضغط في سجل السيارة تقعان قبل الخانق، رغم اسم إحداهما. لا توجد عينة سجل محملة هنا؛ لا تُنقل قراءتهما تلقائيًا إلى MAP بعد الخانق.": "Both vehicle log pressure channels sit before the throttle despite one channel name. No log sample is loaded here; their readings must not be assigned automatically to post-throttle MAP.",
  "map_kpa هو ضغط مطلق محاكى بعد الخانق عند نهاية الإطار؛ ليس قناة ضغط مقاسة من السيارة. الفرق عن ضغط دخل السيناريو معروض للمقارنة بين زمنين موضحين.": "map_kpa is modeled absolute pressure after the throttle at frame end; it is not a measured vehicle pressure channel. Its difference from scenario input pressure compares the two labeled times.",
  "أين يقع الضغط؟": "Where is the pressure?",
  "مسار الهواء ومواقع الضغط": "Air path and pressure locations",
  "مدخل السيناريو": "Scenario input",
  "محاكاة": "Modeled",
  "بدون قراءة": "No reading",
  "زمن الدخل": "Input time",
  "زمن النهاية": "End time",
  "نسبةً إلى ضغط دخل السيناريو": "Relative to scenario input pressure",
  "القيمة المطبعة": "Normalized value",
  "مصدر هذا الموقع": "Source for this location",
  "مسار كثافة الجو وطلب الطريق": "Ambient density and road demand route",
  "المطلق مرجعه الفراغ؛ القياسي هو المطلق ناقص ضغط الجو. اسم القناة لا يحدد موقع حساسها.": "Absolute pressure is referenced to vacuum; gauge pressure is absolute minus atmosphere. A channel name does not establish its sensor location.",
  "لماذا أثق بهذا الرقم؟": "Why trust this number?",
  "الكمية / الموضع:": "Quantity / location:",
  "الوحدة والزمن:": "Unit and time:",
  "الأصل:": "Origin:",
  "حساب محاكاة، وليس قراءة حساس مسجلة.": "Simulation calculation, not a recorded sensor reading.",
  "اشتقاق من مدخل السيناريو؛ ليس حساس ضغط مسجلًا.": "Derived from scenario input; not a recorded pressure sensor.",
  "إحصاء بحثي مسجل في ملف النتائج؛ لا توجد قراءة حية لهذه الكمية هنا.": "Recorded research statistic in the results file; no live reading of this quantity is available here.",
  "افتراض في نموذج المشروع؛ لا توجد قراءة حية له هنا.": "Project-model assumption; no live reading is available here.",
  "غير متاح: لا توجد قراءة حالية لهذه الكمية.": "Unavailable: no current reading of this quantity.",
  "القيمة الحالية:": "Current value:",
  "غير متاحة": "Unavailable",
  "وسام المفهوم يصف أساسه العلمي لا أصل القراءة الحالية.": "The concept badge describes its scientific basis, not the origin of this current reading.",
  "معيار المقارنة: معيار محلي غير موثق بعد. يلزم تطابق المتغير والموضع والوحدات والظروف والزمن ومصدر المرجع قبل الحكم. حرارة غاز العادم ليست معدن التوربين؛ الزيت ليس سائل التبريد.": "Comparison criterion: local criterion not yet documented. Match quantity, location, units, conditions, time and reference source before judging. Exhaust gas is not turbine metal; oil is not coolant.",
  "مثال تاريخي موثق: الزيت": "Documented historical example: oil",
  "أكثر 10 دقائق حرارة؛ النطاق الربيعي لقراءة زيت السيارة. النموذج outside، داخل بيانات الملاءمة؛ ليس اختبارًا مستقلاً ولا نطاقًا مصنعيًا ولا مقارنة بالزمن الحي. موضع الحساس الدقيق غير موثق هنا.": "Hottest 10 minutes; interquartile range of the car oil reading. Model marked outside, in-sample calibration data; not independent validation, a manufacturer range or a live-time comparison. Exact sensor location is not documented here.",
  "اختلاف رقمين لا يثبت خطأ الريدر أو المانيوال؛ ضوضاء الجهاز فرضية للفحص. اختبارات الواجهة ومطابقة المعادلات تختبر التنفيذ، بينما المقارنة التجريبية تختبر تمثيل الواقع ضمن استخدام محدد.": "Two differing numbers do not prove the reader or manual wrong; instrument noise is a hypothesis to investigate. UI tests and equation matching check implementation; experimental comparison checks representation of reality for a defined use.",
  "ماذا تعني loss؟": "What does loss mean?",
  "مثال المصدر هو residual MAPE لتطبيع الحمل، وليس MSE: الحمل النسبي المسجل load_meas وملء الأسطوانات النسبي المحاكى load_model عبر 26 نقطة عند 30–75 kPa.": "The source example is residual MAPE for load normalization, not MSE: logged relative filling/load_meas and modeled relative filling/load_model across 26 points at 30–75 kPa.",
  "مدخلا المقارنة هما الحمل النسبي، وليس خطأ MAP مباشرة.": "Both comparison inputs are relative load, not direct MAP error.",
  "k_fit ملاءمة لمعامل تطبيع واحد؛ الاشتقاق من نسبة كثافتين في المصدر مسار منفصل، وليس اختبارًا مستقلاً للملاءمة.": "k_fit fits one normalization factor; the source’s separate density-ratio derivation is a distinct path, not independent validation of that fit.",
  "هذا خطأ مقارنة بيانات؛ خسائر تدريب SAC ومكافأة التحكم معانٍ مختلفة. لا يتوفر هنا منحنى تدريب أو فاصل ثقة للريدر. حرارة المدخل محاكاة دون حساس بعد المبرد البيني.": "This is data comparison error; SAC training losses and control reward are different quantities. No training curve or reader confidence interval is available here. Intake temperature is modeled without a post-intercooler sensor.",
  "إطار منهجي لتحديد معايير قبول خاصة بالمشروع، وليس إعلان امتثال أو حدود سيارات جاهزة. البروتوكول والعتبات قرار الفريق والدكتور.": "Methodological framework for project-specific acceptance criteria, not a compliance claim or ready-made vehicle limits. Protocol and thresholds require the team and supervisor’s decision.",
  "اختر الزوج": "Select pair",
  "زوج التدريب المختار": "Selected training pair",
  "خفض وسيط مؤشر الضرر عن ECU المرجعية؛ الفرق بين النسب": "Median damage-proxy reduction relative to baseline ECU; difference between percentages",
  "النقطة المئوية ليست نسبة تغير جديدة.": "A percentage point is not a new relative percent change.",
  "تشخيص torque_viol المسجل (median / Q1 / Q3 / worst / best):": "Recorded torque_viol diagnostic (median / Q1 / Q3 / worst / best):",
  "إعداد النسخة المنتجة:": "Producing-version config:",
  "الزوج غير متاح؛ لا نعوّضه بأرقام مصطنعة.": "Pair unavailable; no manufactured values.",
  "التعريف في الشيفرة الحالية: torque_viol هو مجموع cost_torque عبر خطوات الحلقة، وليس نسبة مخالفات أو عددًا أو منحنى لكل خطوة. لا تؤكد هذه الشيفرة وحدها هوية النسخة المنتجة للملف التاريخي المتسخ.": "Current-code definition: torque_viol is the episode sum of cost_torque, not a violation percentage, count or per-step curve. Current code alone does not verify the producing version of the dirty historical artifact.",
  "بذرة التدريب تغيّر تهيئة الشبكة والاستكشاف وعينات التعلم؛ نفس الإعدادات لا تعني نفس الأوزان. هذا تفسير عام للتباين وليس إثباتًا لسبب فرق هذا الزوج. بذور التقييم 1000–1019 لعدد 20 حلقة مجمدة، 720 s وdt=1، صعود 12% / 130 km/h / 42°C وأوزان تكلفة ثابتة. في الجسر المقفل، بذرة الطريق 1000 وأوزان الحلقة المصدرية ثابتة؛ اختيار زوج التدريب لا يغيّر الطريق أو الطقس.": "Training seed affects network initialization, exploration and learning samples; identical settings do not imply identical weights. This is a general explanation of variation, not a proven cause for this pair. Evaluation seeds 1000–1019 cover 20 frozen episodes, 720 s and dt=1, locked 12% / 130 km/h / 42°C climb and fixed cost weights. The locked bridge uses road seed 1000 and its source episode weights; selecting a training pair does not change road or weather.",
  "إعادة تقييم السياسة نفسها لا تسحب فعلاً عشوائيًا كل مرة. إعادة تشغيل أوزان policy.npz المصدّرة ليست النتيجة التاريخية المطابقة لملفات final.zip.": "Evaluating the same policy does not draw a random action each time. Replaying exported policy.npz weights is not the identical historical result scored with final.zip artifacts.",
  "فاصل المجموعة يشمل الصفر: النتيجة غير حاسمة، لا يثبت ذلك انعدام الأثر ولا التعميم لكل سيارة.": "The group interval includes zero: inconclusive, not proof of no effect or generalization to every car.",
  "فاصل المجموعة يحتاج مراجعة.": "Group interval requires review.",
  "سؤال مناقشة: كيف تفرق مكسبًا ثابتًا عن اختيار أفضل seed؟": "Discussion: how do you distinguish a stable gain from choosing the best seed?",
  "فسّر الزوج المختار ثم ارجع إلى كل الأزواج وفاصل المجموعة أعلاه؛ التدريب المتكرر يختلف عن إعادة تشغيل السياسة نفسها. الملاءمة تختلف عن اختبار مستقل، والمقارنة اليدوية predictive تجيب سؤالاً آخر.": "Explain the selected pair, then return to all pairs and the group interval above. Repeated training differs from replaying one policy. Calibration differs from independent testing; the manual predictive comparison answers a different question.",
  "مثال بروتوكول seed 0:": "Seed 0 protocol example:",
  "مسودة الأوامر للخطوة التالية": "Command draft for the next step",
  "صفّر التعديلات · مروحة ومضخة بكامل التشغيل": "Zero trims · fan and pump at full duty",
  "مسودة معلّقة حتى تنفيذ الخطوة التالية؛ تعديلها لا يغيّر زمن الجلسة. القراءات أعلاه تخص العينة المختارة.": "Draft waits for the next step; editing it does not change session time. Readings above belong to the selected sample.",
  "المقارنة تمنع التحرير اليدوي.": "Comparison disables manual editing.",
  "العرض ثلاثي الأبعاد غير متاح في هذا المتصفح.": "3D view is unavailable in this browser.",
  "يمكنك استخدام محدد المكونات والمنحنيات المباشرة ومستكشف المصدر أدناه. فعّل WebGL لعرض المقطع الداخلي.": "Use the component selector, live charts and source explorer below. Enable WebGL to view the cutaway.",
  "تعديلات إشرافية يدوية": "Manual supervisory trims",
  "ECU الأساسية / إشراف محايد": "Baseline ECU / neutral supervision",
  "سياسة يدوية تفاعلية": "Reactive manual policy",
  "سياسة يدوية تعتمد الميل الحالي": "Current-grade manual policy",
  "سياسة يدوية استباقية": "Predictive manual policy",
  "وكيل SAC مطّلع / seed 0": "Sighted SAC agent / seed 0",
  "وكيل SAC أعمى / seed 0": "Blind SAC agent / seed 0",
  "تعذّر تجهيز إعادة تشغيل التسجيل.": "Could not prepare the recorded replay.",
  "الأزرق: هواء من الخارج إلى الأسطوانات. البرتقالي: عادم من المحرك إلى الخارج. اضغط اسم التيربو لفحصه.": "Blue: outside air to cylinders. Orange: exhaust from engine to outside. Select the turbo name to inspect it.",
  "اختر الكتلة أو الزيت أو التوربين لفهم مسار الحرارة، ثم اختبر المروحة والمضخة من بدء بارد ثابت.": "Select block, oil or turbine to understand heat paths, then test fan and pump from a fixed cold start.",
  "بيانات الطريق القادم ← حالة المحرك ← تعديلات المشرف فوق ECU. جرّب حجب المستقبل ومراقبة الخطوة الفعلية.": "Upcoming road → engine state → supervisory trims above ECU. Hide the future and inspect the actual step.",
  "اختر جزءًا، ثم جرّب عَزله أو تفكيك التجميع. غيّر مدخلًا واحدًا لتتابع أثره.": "Select a part, then isolate it or separate the assembly. Change one input to follow its effect.",
  "اختبر فكرة فيزيائية باستخدام النموذج الفعلي، متغيرًا واحدًا في كل مرة.": "Test a physical idea with the actual model, one variable at a time.",
  "اختر مكوّنًا، واتبع علاقاته، ثم افتح تنفيذه الفعلي.": "Select a component, follow its connections and open its implementation.",
  "فكّر في الإجابة قبل كشف شرح المشروع.": "Think of an answer before revealing the project explanation.",
  "هدف مشروع التخرج": "Graduation project objective",
  "فكرة المشروع:": "Project idea:",
  "مشرف يوازن تتبّع العزم والوقود ومؤشر الضرر، مع معرفة ميل الطريق قبل الوصول إليه.": "A supervisor balances torque tracking, fuel and a damage proxy, knowing road grade before reaching it.",
  "1 · السيارة ومسار الهواء": "1 · Vehicle and airflow",
  "2 · التيربو مكبّر": "2 · Turbo detail",
  "3 · رؤية الطريق والقرار": "3 · Road preview and decision",
  "السؤال": "Question",
  "إجابة في 30 ثانية": "30-second answer",
  "الإجابة التقنية": "Technical answer",
  "أجب ذهنيًا أولًا، واستخدم المشهد للإشارة إلى الجزء المقصود.": "Answer mentally first, and use the scene to point to the relevant part.",
  "أخفِ الإجابة": "Hide answer",
  "اكشف الشرح": "Reveal explanation",
  "السؤال التالي": "Next question",
  "جرّب هذا": "Try this",
  "الدرس السابق": "Previous lesson",
  "الدرس التالي": "Next lesson",
  "تجربة حرارية مستقلة؛ لا تغيّر سياسة الطريق أو مسودة المشرف.": "Independent thermal experiment; does not change road policy or supervisory draft.",
  "المشهد الحالي: جلسة الطريق.": "Current scene: road session.",
  "العودة إلى جلسة الطريق": "Return to road session",
  "افتح تجربة المروحة والمضخة المستقلة": "Open independent fan and pump experiment",
  "مصدر المشهد والشرح: تجربة حرارية مستقلة ·": "Scene and explanation source: independent thermal experiment ·",
  "لم يُشغّل المصدر بعد؛ القراءات غير متاحة.": "Source has not run yet; readings unavailable.",
  "طبقة المشهد": "Scene layer",
  "جارٍ إعداد المقطع الداخلي…": "Preparing the cutaway…",
  "وحدة التحكم": "Controller",
  "وحدة التحكم في مختبر الرؤية": "Controller in road-preview lab",
  "طبّق وحدة التحكم": "Apply controller",
  "المثال الأول سياسة يدوية استباقية للتعلّم. تشغيل SAC تعليمي غير موثق ببصمة كاملة للشيفرة؛ النتائج المسجلة في صفحة البحث.": "The first example is a predictive manual policy for learning. SAC replay lacks a complete code fingerprint; recorded results are on the research page.",
  "هواء وشحنة": "Air and charge",
  "عادم وحرارة": "Exhaust and heat",
  "سائل التبريد": "Coolant",
  "زيت": "Oil",
  "مخطط مفاهيمي للنظام · حركة التدفق تعليمية": "Conceptual system diagram · flow motion is illustrative",
  "اختر مكوّنًا": "Select a component",
  "العزم المسلّم": "Delivered torque",
  "طلب العزم": "Torque request",
  "سرعة المحرك": "Engine speed",
  "غاز العادم": "Exhaust gas",
  "حاوية التوربين": "Turbine housing",
  "تدفق الوقود": "Fuel flow",
  "ضغط المانيفولد": "Manifold pressure",
  "تدفق الهواء": "Air flow",
  "محاكاة Python الفعلية": "Actual Python simulation",
  "وحدتا تحكم، وطريق واحد.": "Two controllers, one road.",
  "شغّل حلقة السبب والنتيجة": "Run the cause-and-effect loop",
  "· انتهت الحلقة": "· Episode complete",
  "إيقاف المحاكاة مؤقتًا": "Pause simulation",
  "تشغيل المحاكاة": "Run simulation",
  "إيقاف مؤقت": "Pause",
  "تشغيل": "Run",
  "خطوة واحدة (1 s)": "One step (1 s)",
  "تقدّم 30 ثانية": "Advance 30 seconds",
  "سرعة التشغيل": "Playback speed",
  "0.25× بطيء": "0.25× slow",
  "1× الزمن الفعلي": "1× real time",
  "محاكاة سريعة": "Fast simulation",
  "جارٍ الحساب…": "Calculating…",
  "dt = 1.0 s · لا اتصال بالمركبة": "dt = 1.0 s · no vehicle connection",
  "التجربة": "Experiment",
  "وحدة ECU الأساسية / إشراف محايد": "Baseline ECU / neutral supervision",
  "معاينة ميل الطريق": "Road grade preview",
  "تحميل / إعادة ضبط": "Load / reset",
  "تُطبّق تغييرات الاختيار عند التحميل أو إعادة الضبط. تستخدم «الأساسية» وحدة الإشراف المحايدة في المشروع؛ وقد تختلف أوامر المروحة والمضخة عن جداول ECU الأخرى.": "Selection changes apply on load or reset. Baseline uses the project's neutral supervisor; fan and pump commands may differ from other ECU tables.",
  "عدّل طلب الطريق وأوامر المشرف": "Edit road demand and supervisory commands",
  "استبدال بقية الطريق في هذه التجربة المعزولة": "Replace remaining road in this isolated experiment",
  "تُطبّق التعديلات في الخطوة التالية. قد تختلف القيم المأمورة عن المطبقة بسبب حدود معدل التغيير. وحدات التحكم الأخرى تدير مشغلاتها بنفسها.": "Edits apply at the next step. Requested and applied values may differ because of slew limits. Other controllers manage their own actuators.",
  "تصفّح أشواط المحرك الأربعة": "Explore the four engine strokes",
  "سحب": "Intake",
  "ضغط": "Compression",
  "قدرة": "Power",
  "عادم": "Exhaust",
  "إيقاف الدورة": "Pause cycle",
  "تحريك الدورة": "Animate cycle",
  "اختر طبقة الحرارة لبدء تجربة مستقلة جديدة.": "Select the thermal layer to start a new independent experiment.",
  "شغّل وكيلي SAC المصدّرين، المطلع والأعمى، من بذرة التدريب نفسها. تختلف خانات المعاينة الأربع؛ بينما يتطابق الطريق وحالة البدء وأوزان المكافأة.": "Run the exported sighted and blind SAC agents from the same training seed. Four preview slots differ; road, initial state and reward weights match.",
  "بذرة المقارنة": "Comparison seed",
  "بذرة": "Seed",
  "تحميل الوكيلين": "Load both agents",
  "إعادة تشغيل تعليمية: لأوزان الوكلاء بصمة بيانات، لكن لا تتوفر هوية كاملة للشيفرة. هذه التشغيلات المباشرة ليست النتائج المسجلة للتقييم. افتح النتائج البحثية للاطلاع على التجربة المقترنة الفعلية.": "Educational replay: agent weights have a data fingerprint but no complete code identity. These live runs are not recorded evaluation results. Open research results for the actual paired experiment.",
  "الميل الحالي": "Current grade",
  "التوربين": "Turbine",
  "الوقود": "Fuel",
  "إجمالي الضرر": "Integrated damage",
  "المكافأة": "Reward",
  "ما الذي سجلته المركبة فعلًا؟": "What did the vehicle actually record?",
  "قنوات السجل الأصلية وتقديرات مسار إعادة التشغيل الحالي للقراءة فقط. لا يتوفر ميل الطريق في هذه السجلات.": "Original log channels and current replay estimates are read-only. Road grade is unavailable in these recordings.",
  "تسجيل القيادة": "Drive recording",
  "جارٍ تجهيز إعادة التشغيل…": "Preparing replay…",
  "حمّل تسجيل القيادة": "Load drive recording",
  "المؤشر الزمني للتسجيل": "Recording timeline",
  "سرعة المركبة km/h": "Vehicle speed km/h",
  "حرارة سائل التبريد °C": "Coolant temperature °C",
  "حرارة الزيت °C": "Oil temperature °C",
  "حرارة التوربين °C": "Turbine temperature °C",
  "العزم Nm": "Torque Nm",
  "زمن العينة الأصلية": "Original sample time",
  "تقدير الحرارة في مرحلة الإحماء؛ وعدم اليقين واسع.": "Thermal estimate is warming up; uncertainty is wide.",
  "القنوات المفقودة تبقى غير متاحة.": "Missing channels remain unavailable.",
  "تتبّع السبب والأثر": "Follow cause and effect",
  "اختر رابطًا لفحصه": "Select a connection to inspect",
  "يعتمد اتجاه الأثر على نقطة التشغيل واستجابة التحكم. اختبره بخطوات النموذج؛ فالأسهم علاقات سببية وليست قوانين رتيبة مضمونة.": "Effect direction depends on operating point and control response. Test model steps; arrows show causal relationships, not guaranteed monotonic laws.",
  "ما الذي يعرفه الوكيل؟": "What does the agent know?",
  "23 ملاحظة. خمسة مشغلات.": "23 observations. Five actuators.",
  "يقرأ الوكيل قيمًا مطبّعة، لا كل رقم ظاهر هنا. الملاحظة التالية تختلف عن الملاحظة التي استُخدمت لإنتاج أمر هذه الخطوة.": "The agent reads normalized values, not every number shown here. The next observation differs from the observation that produced this step's command.",
  "اعرض الملاحظات الـ23 وقيمها المطبّعة": "Show all 23 normalized observations",
  "وحدة ECU الأساسية ← المشرف ← المحرك": "Baseline ECU → supervisor → engine",
  "تختار وحدة ECU توقيت الشرارة ولامدا الأساسيين من حالتها. يضيف المشرف التعديلات؛ أما المروحة والمضخة فتُحددان كقيم مطلقة. تغيّر حلقة PI لتتبّع العزم ضغط المانيفولد، ويختار نموذج المركبة ناقل الحركة.": "The ECU chooses baseline spark and lambda from its state. The supervisor adds trims; fan and pump are absolute duties. Torque-tracking PI changes manifold pressure, and the vehicle model chooses gears.",
  "القيم الأساسية لوحدة ECU": "ECU baseline values",
  "شرارة": "Spark",
  "لامدا": "Lambda",
  "تعديل المشرف المطبّق": "Applied supervisory trim",
  "القيمة النهائية بعد حدود المصدر": "Final value after source limits",
  "يُعدّل ضغط المانيفولد عبر حلقة PI لتتبّع العزم، وليس بإضافة التعديل إلى الضغط الأساسي مباشرة. الضغط المرجعي": "Manifold pressure is adjusted by torque-tracking PI, not by adding the trim directly to baseline pressure. Reference pressure",
  "مقابل الضغط تحت الإشراف": "versus supervised pressure",
  "المطلوب": "Requested",
  "المطبّق · حد التغيير ≤": "Applied · slew limit ≤",
  "موازنة الوكيل بين ثلاثة أهداف": "The agent balances three objectives",
  "تحقيق العزم المطلوب، وتقليل الوقود الزائد، وحماية عمر المكونات. تُعاقب أخطاء تتبّع العزم بقوة، لذا فإن رفض العزم مكلف.": "Deliver requested torque, reduce excess fuel and protect component life. Torque-tracking errors are heavily penalized, so refusing torque is costly.",
  "استجابة العزم": "Torque response",
  "وقود موفّر مقارنة بالمرجع": "Fuel saved relative to reference",
  "ضرر متجنّب مقارنة بالمرجع": "Damage avoided relative to reference",
  "المعادلة والأوزان والقيود الفعلية": "Actual equation, weights and constraints",
  "الأوزان (الملاحظات 20–22):": "Weights (observations 20–22):",
  ". الحد الأدنى لوزن تتبّع العزم": ". Minimum torque-tracking weight",
  ". تستخدم الاستجابة دالة عتبة خطية بعد خطأ": ". Response uses a linear hinge after error",
  "، مضروبة في": ", multiplied by",
  "تكاليف التشخيص المعادة: العزم": "Returned diagnostics: torque",
  "، الطرق": ", knock",
  "، وحرارة العادم": ", and exhaust temperature",
  ". هذه للتشخيص؛ لا تضفها إلى المكافأة مرة أخرى. خرج عدم اليقين في وضع الفيزياء يساوي صفرًا.": ". These are diagnostics; do not add them to reward again. Physics-mode uncertainty output is zero.",
  "عتبات الضرر: التوربين": "Damage thresholds: turbine",
  "، والزيت": ", and oil",
  ". هذه افتراضات في مؤشر ضرر نسبي، وليست شهادة أمان أو تلف.": ". These are assumptions in a relative damage proxy, not safety or failure certification.",
  "الجزء المختار · من السبب إلى النتيجة": "Selected part · from cause to outcome",
  "إغلاق شرح الجزء": "Close part explanation",
  "افتح المحرك وجرّب أثره": "Open engine and test its effect",
  "وحدة التحكم / خمسة أفعال": "Controller / five actions",
  "يقرأ obs_in ويختار تعديل الشرارة ولامدا والضغط وأمري المروحة والمضخة. SAC يختار الأفعال ولا يحسب حرارة المعدن.": "Reads obs_in and chooses spark, lambda and pressure trims plus fan and pump commands. SAC chooses actions; it does not calculate metal temperature.",
  "ECU / الحدود / PI": "ECU / limits / PI",
  "قيم ECU الأساسية وحدود التغيير والمشغلات، وحلقة PI لتتبع العزم، تحول طلب المشرف إلى القيم النهائية.": "ECU baselines, actuator and slew limits, and torque-tracking PI convert supervisory requests to final values.",
  "نموذج المحرك": "Engine model",
  "يحسب العزم والوقود وتدفق الهواء وحرارة غاز العادم خلال الفترة من المدخلات النهائية.": "Calculates torque, fuel, airflow and exhaust gas temperature over the interval from final inputs.",
  "الشبكة الحرارية": "Thermal network",
  "تتكامل حالة معدن المحرك والزيت وحاوية التوربين؛ حرارة الغاز ليست حرارة المعدن.": "Integrates engine metal, oil and turbine housing states; gas temperature is not metal temperature.",
  "التقييم / الملاحظة التالية": "Evaluation / next observation",
  "البيئة تجمع مقاديرها والمرجع وأوزان الأهداف للمكافأة ثم تعيد obs للحالة التالية.": "The environment combines its quantities, reference and objective weights into reward, then returns obs for the next state.",
  "لو توقعنا الحرارة فقط، من سيختار الشرارة والمروحة؟": "If we only predicted heat, who would choose spark and fan commands?",
  "هل خفض مؤشر الضرر 12% يعني عمرًا أطول 12%؟": "Does 12% less damage proxy mean 12% longer life?",
  "هل reward قراءة حساس مستقلة أم تصميم أهداف من البيئة والمرجع؟": "Is reward an independent sensor reading or objective design by the environment and reference?",
  "العزم → استجابة العزم": "Torque → torque response",
  "الوقود → جزء الوقود": "Fuel → fuel term",
  "حرارة / طرق → معدل الضرر → جزء الضرر": "Heat / knock → damage rate → damage term",
  "أسطوانة": "Cylinder",
  "وقود": "Fuel",
  "هواء الدخول": "Intake air",
  "يدخل الهواء إلى الضاغط": "Air enters the compressor",
  "المسار الأزرق يوضح دخول الهواء. معدّل الكتلة المعروض محسوب من نقطة تشغيل المحرك.": "Blue shows intake air. Displayed mass flow is calculated from the engine operating point.",
  "الضاغط": "Compressor",
  "يدفع الضاغط الشحنة نحو المحرك": "The compressor pushes charge toward the engine",
  "يرفع الضاغط ضغط الهواء قبل وصوله إلى الأسطوانات. ضغط السحب هنا مدخل مستقل للمحاكي، وليس نتيجة محاكاة دوران التيربو.": "The compressor raises air pressure before cylinders. Intake pressure is an independent simulator input, not a simulated turbo-speed result.",
  "العمود": "Shaft",
  "عمود واحد ينقل الطاقة": "One shaft transfers energy",
  "ينقل العمود دوران التوربين إلى الضاغط ميكانيكيًا. يبقى الهواء والعادم في مسارين منفصلين.": "The shaft mechanically transfers turbine rotation to the compressor. Air and exhaust remain separate.",
  "العادم القادم من المحرك يدير التوربين": "Engine exhaust drives the turbine",
  "المسار البرتقالي يوضح غاز العادم. حرارته من حسابات المحرك؛ حركة ريش التوربين مبطّأة للتعلّم.": "Orange shows exhaust gas. Its temperature comes from engine calculations; turbine blade motion is slowed for learning.",
  "خروج العادم": "Exhaust outlet",
  "يغادر الغاز نحو نظام العادم": "Gas leaves toward the exhaust system",
  "كتلة العادم في النموذج تساوي الهواء والوقود الداخلين. المسار هنا توضيحي؛ لا يعرض محاكاة CFD.": "Model exhaust mass equals incoming air plus fuel. This path is illustrative, not CFD.",
  "تتبّع مساري التيربو": "Follow both turbo paths",
  "عرض المسارين": "Show both paths",
  "هواء": "Air",
  "الأزرق: هواء إلى المحرك · البرتقالي: عادم منه · حركة الجسيمات تمثّل معدّل الكتلة على مقياس مبطّأ.": "Blue: air toward engine · orange: exhaust from engine · particles represent mass flow on a slowed scale.",
  "اختر جزءًا من السيارة أو متغيرًا لتتبّع أسبابه ونتائجه.": "Select a vehicle part or variable to follow its causes and outcomes.",
  "داخل المشروع": "Inside the project",
  "مرجع ECU": "ECU reference",
  "الطلب الفيزيائي": "Physical request",
  "دخل القرار": "Decision input",
  "الأمر المطبّق": "Applied command",
  "نتيجة الفترة": "Interval outcome",
  "حالة النهاية": "End state",
  "لماذا يهم؟": "Why does it matter?",
  "حدود المشروع:": "Project bounds:",
  ". هذا ليس نطاق تشغيل آمنًا متحققًا منه.": ". This is not a validated safe operating range.",
  "ما الذي يغيّره؟": "What changes it?",
  "ما الذي يتأثر به؟": "What does it affect?",
  "إذا غيّرت قيمته": "If you change its value",
  "عند الزيادة:": "When increased:",
  "عند الخفض:": "When decreased:",
  "افتحه في ملفات المشروع": "Open in project files",
  "مقتطف من الشيفرة الأصلية": "Original source excerpt",
  "مصدر للقراءة فقط": "Read-only source",
  "إغلاق المصدر": "Close source",
  "· السطر": "· Line",
  "جارٍ قراءة المصدر المحلي…": "Reading local source…",
  "يعرض هذا المقتطف ملفات المشروع المحلية الحالية. لا يمكن للمتصفح تعديلها.": "This excerpt shows current local project files. The browser cannot edit them.",
  "تجربة نقطة تشغيل": "Operating-point experiment",
  "غيّر مدخلات المحرك، وراقب الاستجابة.": "Change engine inputs and watch the response.",
  "تستدعي هذه التجربة": "This experiment calls",
  "مباشرة. سرعة المحرك وضغط المانيفولد مدخلان مستقلان؛ وقد لا يمثّلان حالة ممكنة للمركبة على الطريق.": "directly. Engine speed and manifold pressure are independent inputs; they may not represent a feasible vehicle road state.",
  "جارٍ حساب دورة المحرك…": "Calculating engine cycle…",
  "احسب دورة المحرك": "Calculate engine cycle",
  "العزم": "Torque",
  "حرارة غاز العادم": "Exhaust gas temperature",
  "مؤشر الطرق": "Knock proxy",
  "زاوية احتراق 50%": "50% burn angle",
  "القدرة": "Power",
  "ابدأ دورة، ثم زد ضغط المانيفولد أو أخّر الشرارة وقارن الاستجابة.": "Start a cycle, then increase manifold pressure or retard spark and compare the response.",
  "الضغط المطلق يشمل الضغط الجوي، أما ضغط التعزيز فهو الزيادة فوقه. لامدا أقل من 1 تعني وقودًا أكثر لكل وحدة هواء. تنبؤات الحمل والحرارة المرتفعين والطرق غير متحقق منها.": "Absolute pressure includes ambient pressure; boost is the excess above it. Lambda below 1 means more fuel per unit air. High-load, thermal and knock predictions are unvalidated.",
  "حرارة التوربين": "Turbine temperature",
  "حرارة العادم": "Exhaust temperature",
  "حرارة الزيت": "Oil temperature",
  "حرارة الكتلة": "Block temperature",
  "معدل الضرر": "Damage rate",
  "توقيت الشرارة": "Spark timing",
  "ميل الطريق": "Road grade",
  "استجابة النظام": "System response",
  "ستظهر المنحنيات بعد تشغيل المحاكاة.": "Charts appear after running the simulation.",
  "استجابة النظام عبر الزمن": "System response over time",
  "راقب الاستجابة": "Watch the response",
  "كل نقطة تمثل خطوة من النموذج": "Each point is one model step",
  "حرّك المؤشر الزمني لاستعراض الخطوات": "Move the timeline to inspect steps",
  "المؤشر الزمني للمحاكاة": "Simulation timeline",
  "الخط المتصل: السياسة المعروضة · المتقطع: السياسة المقارنة": "Solid: displayed policy · dashed: comparison policy",
  "الطريق الذي يراه الوكيل": "The road the agent sees",
  "لا تتوفر بيانات الطريق.": "Road data unavailable.",
  "المعاينة متاحة": "Preview available",
  "خانات المستقبل مصفّرة": "Future slots zeroed",
  "الآن:": "Now:",
  "ميل الطريق عبر الزمن؛ المؤشر عند الزمن الحالي": "Road grade over time; marker at current time",
  "حجب المعاينة يزيل ميل الطريق المستقبلي فقط؛ ويظل الميل الحالي معلومًا لوحدة التحكم.": "Hiding preview removes only future road grade; current grade remains known to the controller.",
  "العربية": "Arabic",
  "جزء استجابة العزم": "Torque response term",
  "جزء الوقود": "Fuel term",
  "جزء الحفاظ على المكونات": "Component preservation term",
  "تكلفة عجز العزم": "Torque shortfall cost",
  "تكلفة الطرق": "Knock cost",
  "تكلفة حرارة العادم": "Exhaust temperature cost",
  "الطريق": "Road",
  "ما قرأه": "What it read",
  "الأمر": "Command",
  "النتيجة": "Outcome",
  "القرار التالي": "Next decision",
  "حلقة قرار المشرف في خمس مراحل": "Five stages of the supervisory decision loop",
  "حلقة واحدة من جلسة المحاكاة الحالية": "One loop from the current simulation session",
  "ماذا يفعل المتحكّم؟": "What does the controller do?",
  "يقرأ الطريق والطلب، ويطبّق أمرًا، ثم نرى ما نتج خلال الخطوة وما بقي في نهايتها.": "It reads road and demand, applies a command, then we see the interval outcome and final state.",
  "توقيت القرار والنتيجة": "Decision and outcome timing",
  "حساب الفترة": "Interval calculation",
  "قبل التنفيذ": "Before execution",
  "حرارة النهاية": "End temperature",
  "حالة البداية": "Initial state",
  "شاهد مثالًا قبل الصعود": "See an example before the climb",
  "مراحل حلقة القرار": "Decision-loop stages",
  "ما قرأه المشرف ← الأمر ← النتيجة ← الحالة الجديدة": "Supervisor input → command → outcome → new state",
  "يرى الطريق القادم": "It sees the upcoming road",
  "الميل الحالي يبقى معلومًا حتى عند حجب المعاينة المستقبلية.": "Current grade remains known even when future preview is hidden.",
  "الميل عند دخل القرار": "Grade at decision input",
  "درجات الطريق عند آفاق المعاينة": "Road grades at preview horizons",
  "هذه معاينة من مسار التجربة، وليست قراءة كاميرا أو حساس طريق.": "This preview comes from the experiment route, not a camera or road sensor.",
  "حجب معاينة المستقبل": "Hide future preview",
  "إظهار معاينة المستقبل": "Show future preview",
  "ماذا قرأت السياسة؟": "What did the policy read?",
  "ملاحظة الدخل أنتجت الأمر. طلبها مخزّن من الخطوة السابقة؛ طلب الفترة يُحسب بعد اختيار الأمر.": "Input observation produced the command. Its demand is stored from the previous step; interval demand is calculated after choosing the command.",
  "طلب العزم الذي رأته السياسة": "Torque demand seen by the policy",
  "حرارة الدخل من نهاية العينة السابقة المطابقة؛ لا نستعمل حرارة نهاية الفترة كأنها كانت متاحة قبل الأمر.": "Input temperature comes from the matching previous sample's end; interval-end heat was not available before the command.",
  "عند الدخل": "At input",
  "يعدّل فوق وحدة ECU": "It adjusts above the ECU",
  "ثلاثة تعديلات على خرج ECU؛ المروحة والمضخة أوامر تشغيل مطلقة.": "Three ECU output trims; fan and pump are absolute duty commands.",
  "وحدة التحكم الحالية": "Current controller",
  "اختر مشغلًا": "Select an actuator",
  "· النتيجة خلال": "· Outcome during",
  ". حد التغيير": ". Slew limit",
  "، وزمن الخطوة": ", and step duration",
  ". قد يختلف الطلب عن المطبّق بسبب حد التغيير وحدود المشغل": ". Requested and applied values may differ because of slew and actuator limits",
  "ضغط المانيفولد ناتج حلقة PI لتتبّع العزم مع تعديل الضغط؛ المرجع حلقة موازية، وليس المرجع + التعديل.": "Manifold pressure comes from torque-tracking PI with pressure trim; the reference is a parallel loop, not reference plus trim.",
  "المروحة والمضخة أوامر مطلقة؛ مرجع المروحة للمقارنة فقط، ومرجع المضخة غير مُصدّر.": "Fan and pump are absolute commands; fan reference is for comparison only, and pump reference is not exported.",
  "تعديل المشرف يضاف إلى مرجع ECU، ثم تُطبّق حدود المصدر؛ القيمة النهائية المعروضة مُصدّرة من المحاكاة.": "Supervisory trim adds to ECU baseline, then source limits apply; the displayed final value is exported by the simulation.",
  "ماذا نتج؟": "What happened?",
  "مخرجات الفترة": "Interval outputs",
  "محسوبة بالنموذج.": "calculated by the model.",
  "العزم المتحقق": "Delivered torque",
  "غاز العادم خلال الفترة": "Exhaust gas during the interval",
  "طلب الفترة ليس بالضرورة الطلب الذي رأته السياسة. عند البداية تبقى النتائج غير متاحة حتى تنفيذ أمر.": "Interval demand may differ from policy input demand. At initialization, outcomes remain unavailable until a command executes.",
  "ماذا بقي للقرار التالي؟": "What remains for the next decision?",
  "الحالة عند": "State at",
  "تدخل الملاحظة التالية.": "enters the next observation.",
  "الدخل ← النهاية · الفرق": "Input → end · difference",
  "لا توجد عينة سابقة مطابقة من هذه الجلسة؛ حرارة الدخل والفرق غير متاحين.": "No matching previous sample from this session; input heat and difference are unavailable.",
  "معدل الضرر عند النهاية": "Damage rate at interval end",
  "الضرر المتراكم في الجلسة": "Integrated session damage",
  "مجموع مؤشر الضرر المتكامل منذ بداية الجلسة، وليس معدل هذه اللحظة.": "Integrated damage proxy accumulated since session start, not the instantaneous rate.",
  "الضرر مؤشر تقريبي؛ لا يتنبأ بالعمر الفعلي للمكونات.": "Damage is a proxy; it does not predict actual component life.",
  "الملاحظة والمكافأة بالتفصيل": "Observation and reward details",
  "نعيد تشغيل سياسة جاهزة. عرض المكافأة لا يعني تدريبًا مباشرًا؛ لا تتغير أوزان السياسة أثناء هذا التشغيل.": "We replay a ready policy. Displaying reward does not mean live training; policy weights do not change during this run.",
  "مكافأة الانتقال": "Transition reward",
  "مكافأة الانتقال:": "Transition reward:",
  "قيم الملاحظة مطبّعة كما يعيدها المصدر؛ obs_in قبل الأمر، وobs بعده. لا تُجمع هذه الحقول يدويًا لصنع مكافأة جديدة.": "Observation values are normalized as returned by the source; obs_in before the command, obs after it. Do not sum these fields manually to create a new reward.",
  "الدخل": "Input",
  "← ملاحظة القرار التالي": "→ next decision observation",
  "خانة": "Slot",
  "السابق": "Previous",
  "التالي": "Next",
  "جارٍ تحديث الخطوة…": "Updating step…",
  "نفّذ الخطوة التالية": "Execute next step",
  "على الصعود، يزيد كل وكيل توقيت الشرارة": "On the climb, each agent advances spark",
  "عن المرجع (الحد الأعلى للتعديل": "past baseline (trim upper bound",
  "؛ وتوقيت المرجع هناك": "; baseline spark there",
  "). يرفع ذلك مؤشر الطرق المحاكى من": "). This raises the modeled knock integral from",
  "إلى": "to",
  "(المئين 95)، دون العتبة المفترضة": "(95th percentile), below the assumed knee",
  ". قد يفسر هذا جزءًا من مكسب الوكلاء على السياسات اليدوية، اعتمادًا على نموذج طرق غير متحقق منه. الاستباق لا يتأثر لأن السياستين المطلعة والعمياء تفعلان ذلك معًا.": ". This may explain part of the agents' advantage over manual policies, relying on an unvalidated knock model. Preview is unaffected because both sighted and blind policies do this.",
  "يذكر التقرير أن تقديم الشرارة يفسر جزءًا من فارق الوكلاء، لكن هذا التفسير يعتمد على نموذج طرق غير متحقق منه.": "The report attributes part of the agent gap to spark advance, but this interpretation depends on an unvalidated knock model.",
  "سجّل الوكيل الأعمى seed6 ضررًا أعلى من وحدة التحكم الأساسية في": "Blind agent seed6 recorded higher damage than baseline in",
  "من": "of",
  "حلقة (أرقامها": "episodes (numbers",
  "). أسوأ قيمة": "). Worst value",
  "مقابل": "versus",
  "للمرجع، وبلغت حرارة التوربين": "for baseline; peak turbine temperature",
  ". لذلك لا تضمن النتيجة الوسيطة حماية كل حلقة.": ". A median result therefore does not guarantee protection in every episode.",
  "سجّل أحد الوكلاء ضررًا أعلى من وحدة التحكم الأساسية في بعض الحلقات؛ لذلك لا تضمن النتيجة الوسيطة حماية كل حلقة.": "An agent recorded higher damage than baseline in some episodes; a median result does not guarantee protection in every episode.",
  "تفوقت": "Outperformed:",
  "وكيلًا على أفضل سياسة يدوية في وسيط خفض الضرر (": "agents versus the best manual policy on median damage reduction (",
  "). واستهلك": "). And",
  "وكلاء وقودًا أقل من المرجع.": "agents consumed less fuel than baseline.",
  "تفوقت الوكلاء في وسيط الضرر، بينما استهلك بعضهم وقودًا أقل من المرجع.": "Agents improved median damage, while some consumed less fuel than baseline.",
  "ملاحظة واردة في التقرير المولد؛ افتح ملف النتيجة لقراءة النص الأصلي.": "Finding from the generated report; open the result file for the original text.",
  "ملخص الوكلاء واختبار الاستباق ومصدر التدريب": "Agent summary, preview test and training provenance",
  "جدول الاستئصال والفروق بين البذور": "Ablation table and seed differences",
  "تشخيص تقييد تقديم الشرارة": "Spark-advance constraint diagnostic",
  "نتائج السياسات اليدوية على النموذج الحالي": "Manual-policy results on the current model",
  "جارٍ قراءة ملفات النتائج الحالية…": "Reading current result files…",
  "النتيجة البحثية الحالية غير متاحة. لن نستبدلها بأرقام تاريخية.": "Current research result unavailable. Historical numbers will not substitute for it.",
  "تغيّرت النتيجة المقترنة وتحتاج إلى مراجعة قبل عرض هذا الاستنتاج التعليمي. افتح مصدر النتيجة الحالية.": "The paired result changed and requires review before presenting this learning conclusion. Open the current result source.",
  "اقرأ ملف النتائج": "Read result file",
  "ماذا أظهرت التجربة؟": "What did the experiment show?",
  "تحسن وسيط الضرر مع الإشراف.": "Median damage improved with supervision.",
  "وأثر الاستباق غير حاسم.": "The preview effect is inconclusive.",
  "غير حاسم": "Inconclusive",
  "متوسط أفضلية الاستباق": "Mean preview advantage",
  "فاصل الثقة 95%:": "95% confidence interval:",
  "عبر": "across",
  "أزواج من البذور. يشمل الفاصل الصفر وآثارًا قد تكون مهمة.": "seed pairs. The interval includes zero and potentially meaningful effects.",
  "فاصل الثقة لأفضلية الاستباق": "Confidence interval for preview advantage",
  "مجموعة النتائج:": "Result set:",
  "· تاريخ الإنشاء": "· Generated",
  "وكيل SAC · ميزانية التدريب": "SAC agents · training budget",
  "خطوة · تقييم التسلق المقفل عند": "steps · locked climb evaluation at",
  "يسجل التقرير صفر حلقات جرى فحص تراجعها.": "The report records zero regression-checked episodes.",
  "اختلاف البذور أكبر من متوسط الأثر": "Seed variation exceeds the mean effect",
  "البذرة": "Seed",
  "رجّح الاستباق": "Favored preview",
  "تفوقت السياسة العمياء": "Blind policy performed better",
  "السياسات المكتوبة يدويًا تجيب عن سؤال مختلف.": "Manual policies answer a different question.",
  "في الفرضية الحالية، الفرق بين الحماية التنبؤية والحماية المعتمدة على الميل الحالي هو": "In the current premise, predictive protection differs from current-grade protection by",
  ". والفرق الأكبر عن سياسة الحرارة التفاعلية البحتة": ". The larger gap against purely reactive thermal protection is",
  ". يظل الميل الحالي متاحًا دون الاستباق.": ". Current grade remains available without preview.",
  "افتح مصدر الفرضية": "Open premise source",
  "اعرض المقارنات كلٌّ على حدة": "View comparisons separately",
  "اعرض الضرر الكلي": "Show total damage",
  "اعرض الضرر الحراري فقط": "Show thermal damage only",
  "الضرر مؤشر تقريبي، وليس عمر مكونات مقاسًا.": "Damage is a proxy, not measured component life.",
  "يعتمد مكسب وسيط السياسات المتعلمة بدرجة كبيرة على تقديم الشرارة قرب عتبة الطرق غير المتحقق منها.": "Learned policies' median gain depends strongly on spark advance near the unvalidated knock knee.",
  "تشخيص تقييد الشرارة غير متاح.": "Spark-constraint diagnostic unavailable.",
  "لم تُدرّب الوكلاء مع هذا القيد؛ لذا فهذا تشخيص خارج توزيع التدريب. وقد يخفي الوسيط حلقات ضارة.": "Agents were not trained with this constraint; this is an out-of-training-distribution diagnostic. The median may conceal harmful episodes.",
  "افتح تشخيص هامش الطرق": "Open knock-margin diagnostic",
  "ما الذي رصده التقرير المولد؟": "What did the generated report observe?",
  "التفاصيل الإحصائية ومصادر البيانات": "Statistics and data sources",
  "قيمة اختبار t هي": "t-test value is",
  "؛ وقيمة اختبار Wilcoxon هي": "; Wilcoxon value is",
  ". وهما يختلفان عن معيار MEI المسجل مسبقًا بوحدات الضرر. متوسط أثر الاستباق الحراري فقط:": ". These differ from preregistered MEI in damage units. Mean thermal-only preview effect:",
  "افتح المصدر": "Open source",
  "تنتمي تجارب Phase D وD2 وC4 الأقدم إلى نموذج سابق؛ ولا تدخل في هذه النتيجة الرئيسة.": "Earlier Phase D, D2 and C4 experiments use an older model and do not enter this main result.",
  "عمود المرفق": "Crankshaft",
  "يحوّل حركة المكابس صعودًا وهبوطًا إلى دوران.": "Converts piston motion into rotation.",
  "المكابس والأذرع": "Pistons and connecting rods",
  "ضغط الاحتراق يدفع المكبس؛ والذراع ينقل القوة إلى العمود.": "Combustion pressure pushes the piston; the rod transfers force to the shaft.",
  "رأس المحرك": "Cylinder head",
  "يضم الصمامات وممرات دخول الهواء وخروج العادم.": "Contains valves and intake/exhaust passages.",
  "شمعات الإشعال": "Spark plugs",
  "تقديم الشرارة يغيّر توقيت الاحتراق في حسابات النموذج.": "Spark advance changes combustion timing in model calculations.",
  "كتلة المحرك": "Engine block",
  "تحتوي الأسطوانات؛ وحرارتها عقدة مجمّعة في النموذج.": "Contains cylinders; its heat is a lumped model node.",
  "حوض الزيت": "Oil pan",
  "يجمع الزيت؛ ويُمثّل حراريًا بحالة واحدة في النموذج.": "Collects oil; represented thermally by one model state.",
  "صمامات السحب": "Intake valves",
  "تدخل الشحنة في شوط السحب. حركة الصمام هنا تعليمية.": "Charge enters during intake. Valve motion here is illustrative.",
  "صمامات العادم": "Exhaust valves",
  "تخرج الغازات في شوط العادم. التدفق هنا توضيحي.": "Gas leaves during exhaust. Flow here is illustrative.",
  "البخاخ والوقود": "Injector and fuel",
  "البخاخ علامة تعليمية مستقلة عن شمعة الإشعال. لامدا أقل من 1 تعني وقودًا أكثر لكل وحدة هواء.": "Injector is a teaching marker separate from the spark plug. Lambda below 1 means more fuel per unit air.",
  "محجوب": "Hidden",
  "أوقف الحركة": "Pause motion",
  "حرّك الآلية": "Animate mechanism",
  "سرعة الحركة التعليمية": "Illustrative motion speed",
  "بطيئة جدًا": "Very slow",
  "بطيئة": "Slow",
  "عادية": "Normal",
  "إعادة بداية الدورة": "Restart cycle",
  "افحص الدورة": "Inspect cycle",
  "زاوية دورة المحرك التعليمية": "Illustrative engine-cycle angle",
  "تدفق العادم": "Exhaust flow",
  "حرارة المحرك": "Engine temperature",
  "دوران المحرك": "Engine rotation",
  "ضغط السحب": "Intake pressure",
  "نموذج السوبرا التفاعلي": "Interactive Supra model",
  "درس الأسطوانة": "Cylinder lesson",
  "شرح الدورة": "Cycle explanation",
  "العودة إلى السيارة": "Return to vehicle",
  "اختر أسطوانة": "Select a cylinder",
  "محطات الدورة التعليمية": "Illustrative cycle stations",
  "لحظة الشرارة": "Spark moment",
  "توقيت الشرارة غير متاح": "Spark timing unavailable",
  "أمر الإشعال عند": "Ignition command at",
  "عند النقطة الميتة العليا": "At top dead center",
  "° قبل النقطة الميتة العليا": "° before top dead center",
  "° بعد النقطة الميتة العليا": "° after top dead center",
  "الومضة 8° توضيحية؛ يبدأ الاحتراق ثم يستمر بعد انطفائها. النقطة الميتة العليا للضغط عند 360°.": "The 8° flash is illustrative; combustion continues after it. Compression TDC is at 360°.",
  "الشوط الحالي": "Current stroke",
  "· سحب · تدخل الشحنة وينزل المكبس.": "· Intake · charge enters and piston descends.",
  "حالة الصمامين وحركة المكبس": "Valve state and piston motion",
  "السحب:": "Intake:",
  "مفتوح": "Open",
  "مغلق": "Closed",
  "العادم:": "Exhaust:",
  "↑ المكبس يصعد": "↑ Piston rising",
  "↓ المكبس ينزل": "↓ Piston descending",
  "الرأس مفصول للتعلّم؛ التدفق داخل الحجرة متوقف. أعد التجميع لتتبع الشحنة.": "Head separated for learning; chamber flow paused. Reassemble to follow the charge.",
  "المسار الوردي: وقود من مسطرة التغذية → البخاخ → منفذ السحب → الشحنة داخل الحجرة. الزيت بلون بني. مسار الحقن وتوقيته رسم تعليمي، لا يصفان هندسة B58 المصنعية. الشمعة تبدأ الاحتراق.": "Pink: fuel rail → injector → intake port → chamber charge. Oil is brown. Injection path and timing are illustrative, not factory B58 geometry. The plug initiates combustion.",
  "قيم النموذج الحالية": "Current model values",
  "ميل الطريق القادم": "Upcoming road grade",
  "بعد": "After",
  "ث": "s",
  "إغلاق العرض الموسّع": "Close expanded view",
  "توسيع المختبر": "Expand lab",
  "تكبير النموذج": "Zoom in",
  "تصغير النموذج": "Zoom out",
  "إعادة المنظور": "Reset view",
  "زوايا الفحص": "Inspection angles",
  "منظور حر": "Free view",
  "أمامي": "Front",
  "جانبي": "Side",
  "علوي": "Top",
  "مقطع الأسطوانة": "Cylinder cutaway",
  "تدوير تلقائي": "Auto rotation",
  "الجزء المختار": "Selected part",
  "غلاف الضاغط": "Compressor housing",
  "غلاف التوربين": "Turbine housing",
  "التيربو: مساران وعمود واحد": "Turbo: two paths, one shaft",
  "يوجّه الهواء من مركز الضاغط إلى المخرج المحيطي. ضغط السحب مدخل مستقل لنقطة التشغيل.": "Directs air from compressor center to peripheral outlet. Intake pressure is an independent operating-point input.",
  "يحيط الغلاف بالدوّار ويوجّه الغاز. حرارة الغلاف عقدة حرارية مستقلة؛ لا نستنتجها من حرارة غاز العادم.": "Housing surrounds the rotor and directs gas. Housing heat is an independent thermal node; we do not infer it from exhaust gas heat.",
  "الهواء الأزرق يدخل الضاغط؛ والعادم البرتقالي يدير التوربين. العمود يربط الدوّارين دون خلط الغازين.": "Blue air enters the compressor; orange exhaust drives the turbine. The shaft connects rotors without mixing gases.",
  "ركّز عليه": "Focus on it",
  "عرض التجميع": "Assembly view",
  "عزل الجزء": "Isolate part",
  "اتبع الهواء والعادم": "Follow air and exhaust",
  "هواء خارجي → فلتر → ضاغط التيربو → مبرد الشحنة → مجمع السحب → منافذ الرأس → الأسطوانات": "Outside air → filter → turbo compressor → intercooler → intake manifold → head ports → cylinders",
  "الأسطوانات → منافذ العادم → التوربين → أنبوب العادم → خارج السيارة": "Cylinders → exhaust ports → turbine → exhaust pipe → outside vehicle",
  "اتبع أسطوانة واحدة": "Follow one cylinder",
  "افحص التيربو مكبّرًا": "Inspect enlarged turbo",
  "الأسهم وفروع الأسطوانات رسم تعليمي؛ تدفق الهواء والعادم الكلي من النموذج. تجربة نقطة المحرك مستقلة عن جلسة الطريق.": "Arrows and cylinder branches are illustrative; total air and exhaust flow comes from the model. Engine-point experiment is independent of the road session.",
  "أمام السيارة: خانات المستقبل التي تصل للمشرف. التباعد بين الخانات رسم توضيحي؛ الآفاق بالثواني وليست مسافات مقاسة.": "Ahead of the car: future slots sent to the supervisor. Spacing is illustrative; horizons are in seconds, not measured distances.",
  "اختيار جزء من المحرك": "Select an engine part",
  "طريقة عرض الأجزاء": "Part appearance",
  "كامل": "Solid",
  "شفاف": "Transparent",
  "مقطع": "Section",
  "تفكيك تعليمي": "Illustrative separation",
  "تفكيك أجزاء التيربو": "Separate turbo parts",
  "تفكيك أجزاء المحرك": "Separate engine parts",
  "إعادة التجميع": "Reassemble",
  "حركة وأبعاد تفكيك توضيحية؛ القيم من المحاكي الأصلي.": "Illustrative motion and separation dimensions; values from the original simulator.",
  "الدورة 720°؛ الحركة مبطّأة.": "720° cycle; motion slowed.",
  "حركة الدوّار مبطّأة؛ سرعة التيربو غير محسوبة.": "Rotor motion slowed; turbo speed is not calculated.",
  "مسارات التدفق تعليمية.": "Flow paths are illustrative.",
  "الحركة التلقائية متوقفة حسب تفضيل جهازك.": "Automatic motion disabled by your device preference.",
  "الأجزاء مكشوفة": "Parts exposed",
  "أظهر الهيكل": "Show body shell",
  "اكشف الأجزاء": "Expose parts",
  "أوقف حركة المسار": "Pause path motion",
  "حرّك المسار": "Animate path",
  "حركة الأشواط مبطّأة": "Stroke motion slowed",
  "السحب: يدخل الهواء والوقود": "Intake: air and fuel enter",
  "الضغط: يصعد المكبس": "Compression: piston rises",
  "القدرة: يدفع الاحتراق المكبس": "Power: combustion pushes piston",
  "العادم: تخرج الغازات": "Exhaust: gas leaves",
  "اسحب لتدوير السيارة · اضغط الجزء لتفهمه": "Drag to rotate the vehicle · select a part to understand it",
  "حركة توضيحية؛ لا تغيّر المحاكاة": "Illustrative motion; does not change the simulation",
  "تقديم الشرارة": "Spark advance",
  "تجربة نقطة تشغيل المحرك": "Engine operating-point experiment",
  "نقطة تشغيل مباشرة": "Direct operating point",
  "مدخلات المحرك": "Engine inputs",
  "غيّر مدخلًا لمعاينة استجابة المحرك.": "Change one input to see engine response.",
  "جارٍ الحساب · تظهر آخر نتيجة": "Calculating · last result displayed",
  "تعذّر الحساب · تظهر آخر نتيجة": "Calculation failed · last result displayed",
  "تعذّر الحساب": "Calculation failed",
  "نتيجة النموذج": "Model result",
  "بانتظار المدخلات": "Waiting for inputs",
  "مقارنة مرجعية": "Reference comparison",
  "ثبّت المرجع": "Pin reference",
  "ارجع للمرجع": "Restore reference",
  "امسح المرجع": "Clear reference",
  "المرجع": "Reference",
  "نتيجة ناجحة محفوظة": "Saved successful result",
  "آخر نتيجة ناجحة": "Last successful result",
  "الحالي · آخر نتيجة ناجحة": "Current · last successful result",
  "القيمة": "Value",
  "الحالي": "Current",
  "الفرق": "Difference",
  "فرق عددي؛ الزيادة ليست أفضل دائمًا.": "Numerical difference; higher is not always better.",
  "تنبيهات نقطة التشغيل (": "Operating-point warnings (",
  "هذه مدخلات مستقلة للنموذج؛ لا تمثل بالضرورة حالة ممكنة للمركبة على الطريق. لا تُستنتج منها حرارة الزيت أو الكتلة أو التوربين.": "Independent model inputs may not represent a feasible vehicle road state. Oil, block and turbine temperatures cannot be inferred from them.",
  "أسباب الحرارة ومساراتها": "Heat causes and paths",
  "الكتلة وسائل التبريد / الرديتر: المسار غير نشط؛ منظم النموذج مغلق": "Block/coolant / radiator: path inactive; model thermostat closed",
  "غاز أزرق/برتقالي · سائل أزرق/ذهبي · طاقة بنفسجية متقطعة؛ الأسهم انتقال طاقة وليست أنابيب.": "Blue/orange gas · blue/gold liquid · dashed purple energy; arrows transfer energy, not pipes.",
  "الزمن والمنظم ومصادر النموذج": "Time, thermostat and model sources",
  "تجربة حرارية مستقلة ·": "Independent thermal experiment ·",
  "البداية": "Initialization",
  "تسخين": "Heating",
  "تبريد": "Cooling",
  "جلسة الطريق": "Road session",
  "· حرارة العينة المعروضة عند": "· Displayed sample heat at",
  ". بعد البداية، الغاز ومدخل الوقود والدوران يخصّان فترة الحساب السابقة؛ الاتجاه المعروض مقارنة حدود الغاز وحرارة النهاية، وليس قياس تدفق حراري لحظي.": ". After initialization, gas, fuel and rotation inputs belong to the preceding calculation interval; shown direction compares gas boundary and end temperature, not instantaneous heat-flow measurement.",
  "منظم حراري بديل في النموذج: يتجاوز الرديتر تحت منطقة الفتح، ويتدرج تأثير المروحة والمضخة مع الفتح. آخر فتح محسوب قبل آخر تحديث حرارة (0.1 s في التجربة؛ خطوة الطريق في الجلسة):": "Surrogate model thermostat: bypasses radiator below opening region; fan and pump influence increases with opening. Last opening calculated before the latest thermal update (0.1 s in experiment; road timestep in session):",
  ". نظام B58 الفعلي لإدارة الحرارة مختلف.": ". Actual B58 thermal management differs.",
  "التوربين يتبادل مع الغاز والجو فقط؛ لا وصلة تبريد مباشرة من المروحة أو المضخة.": "Turbine exchanges heat only with gas and ambient; no direct fan or pump cooling link.",
  "الوقود مصدر للكتلة والزيت؛ الزيت يستقبل أيضًا احتكاك الدوران وتحريكه. تبادل الزيت والكتلة ينعكس مع فرق الحرارة.": "Fuel heats block and oil; oil also receives rotational friction and churning. Oil/block exchange reverses with temperature difference.",
  "أزيل الوقود والعادم؛ حد الغاز هو الجو، لكن دوران 800 RPM يبقى وقد ينتج حرارة زيت.": "Fuel and exhaust removed; gas boundary is ambient, but 800 RPM remains and may heat oil.",
  "· ثلاث عقد مجمعة ومسارات تعليمية، لا مخطط تبريد مصنعي ولا قيم واط.": "· Three lumped nodes and illustrative paths, not a factory cooling diagram or watt values.",
  "الكتلة / سائل التبريد": "Block / coolant",
  "الزيت": "Oil",
  "هيكل التوربين": "Turbine housing",
  "المروحة": "Fan",
  "المضخة": "Pump",
  "مدة التسخين": "Heating duration",
  "مدة التبريد": "Cooling duration",
  "الجو": "Ambient",
  "الشرارة": "Spark",
  "طريقة المصدر": "Source method",
  "حالة البدء": "Initial state",
  "قيم إطار البدء": "Initial-frame values",
  "تبريد · RPM 800، وقود وعادم صفر": "Cooling · 800 RPM, zero fuel and exhaust",
  "بداية باردة": "Cold start",
  "تجربة المروحة والمضخة المستقلة": "Independent fan and pump experiment",
  "تجربة مستقلة · ThermalNetwork": "Independent experiment · ThermalNetwork",
  "ثبّت المرجع، ثم غيّر التبريد.": "Pin reference, then change cooling.",
  "المروحة والمضخة تعدّلان فقد الرديتر عبر منظم النموذج. لا يوجد اتصال مباشر منهما إلى عقدة التوربين؛ تساوي منحناه أو انغلاق المنظم نتيجة مفيدة.": "Fan and pump adjust radiator loss through the model thermostat. Neither directly connects to the turbine node; matching turbine curves or a closed thermostat are informative outcomes.",
  "إعدادات المسودة · لا تطبّق حتى التشغيل": "Draft settings · apply on run",
  "نقطة التسخين الثابتة:": "Fixed heating point:",
  ". الجو 42°C، التبريد 90 s، بدء جميع العقد عند الجو، تكامل المصدر 0.1 s.": ". Ambient 42°C, cooling 90 s, all nodes start at ambient, source integration 0.1 s.",
  "المسودة تغيّرت؛ القيم والمنحنيات أدناه تخص آخر تشغيل محفوظ.": "Draft changed; readings and curves below belong to the last saved run.",
  "تغييرات المسودة عن المرجع:": "Draft changes from reference:",
  "لا تغيير": "No change",
  "· مقارنة التبريد غير صالحة: أعد إعدادات المرجع أو شغّل ثم ثبّت مرجعًا جديدًا.": "· Cooling comparison invalid: restore reference settings or run and pin a new reference.",
  "جارٍ حساب المصدر…": "Calculating source…",
  "شغّل إعدادات المسودة من البدء نفسه": "Run draft from the same start",
  "شغّل التسخين والتبريد": "Run heating and cooling",
  "ثبّت النتيجة الحالية مرجعًا": "Pin current result as reference",
  "استعد إعدادات المرجع ونتيجته": "Restore reference settings and result",
  "النتيجة المحفوظة: مروحة": "Saved result: fan",
  "، مضخة": ", pump",
  "، تسخين": ", heating",
  "s، تبريد": "s, cooling",
  "مقارنة صالحة · الإعدادات متساوية": "Valid comparison · identical settings",
  "ثبّت النتيجة مرجعًا لإظهار الفروق.": "Pin result to show differences.",
  "اختر زمن المصدر:": "Select source time:",
  "المؤشر الزمني للتجربة الحرارية": "Thermal experiment timeline",
  "المرجع عند الزمن نفسه:": "Reference at the same time:",
  "الحالي − المرجع:": "Current − reference:",
  "لا توجد عينة مشتركة عند هذا الزمن الفعلي؛ لا نستوفي قيمًا بين العينات.": "No shared sample at this actual time; no interpolation between samples.",
  "━━ النتيجة الحالية": "━━ Current result",
  "┄┄ المرجع": "┄┄ Reference",
  "· الزمن المنقضي نفسه، ومحور حرارة مشترك لكل عقدة": "· Same elapsed time and shared temperature axis for each node",
  "· منحنى النتيجة المحفوظة فقط؛": "· Saved-result curve only;",
  "المقارنة غير صالحة": "Comparison invalid",
  "لم يُثبّت مرجع بعد": "No reference pinned yet",
  "طريقة المصدر وحدود التجربة": "Source method and experiment limits",
  "التسخين يستخدم plant.predict عند نقطة ثابتة وECT=الجو، وحرارة الشحنة الافتراضية أعلى من الجو 12 K دون مدخل من الكتلة. التبريد: RPM 800، تدفق الوقود والعادم صفر؛ حد الغاز هو الجو وحرارة غاز العادم غير متاحة. المحرك ليس متوقفًا بالكامل. معاملات الحاوية افتراضية، وعقدة الكتلة المعايرة تتذبذب عند خطوات كبيرة؛ نستخدم تكامل المصدر 0.1 s.": "Heating uses plant.predict at a fixed point with ECT=ambient; default charge temperature is ambient +12 K without block feedback. Cooling: 800 RPM, zero fuel and exhaust; gas boundary is ambient and exhaust temperature unavailable. Engine is not fully stopped. Housing coefficients are assumed; calibrated block oscillates at large steps, so source integration uses 0.1 s.",
  "حالة البدء:": "Initial state:",
  "هواء خارجي": "Outside air",
  "التيربو": "Turbo",
  "هواء إلى الأسطوانات": "Air to cylinders",
  "مقاس فعليًا": "Measured",
  "مستخرج من البيانات": "Derived from data",
  "افتراض": "Assumed",
  "غير متحقق منه": "Unvalidated",
  "إعادة تشغيل غير موثقة": "Unverified replay",
  "مدخل التجربة": "Scenario input",
  "منشور": "Published",
  "نتيجة إحصائية": "Recorded statistic",
  "مصادر مختلطة": "Mixed sources",
  "ضغط المانيفولد خارج نطاق 30–75 kPa الذي شملته مقارنة تعبئة الهواء وتدفقه في 26 نقطة؛ هذه المقارنة لا تثبت دقة النتيجة هنا.": "MAP is outside the 30–75 kPa range of the documented 26-point filling/airflow residual comparison; that check does not establish accuracy here.",
  "ضغط المانيفولد المطلوب يتجاوز الحد التشغيلي المستنتج من السجلات عند تدفق الهواء الذي يتنبأ به النموذج؛ هذه النقطة ليست حالة ممكنة للمركبة.": "Requested MAP exceeds the log-derived vehicle ceiling at model-predicted airflow; this direct lab point is not vehicle-feasible.",
  "ضغط المانيفولد المطلوب قريب من الحد التشغيلي المستنتج من السجلات عند تدفق الهواء الذي يتنبأ به النموذج.": "Requested MAP is near the log-derived vehicle ceiling at model-predicted airflow.",
  "بلغت المحاكاة الحد الأقصى للجلسات المفتوحة. أعد ضبط جلسة أو أغلقها.": "Simulation session capacity reached. Reset or close a session.",
  "انتهت هذه الجلسة. ابدأ جلسة جديدة للمتابعة.": "This session is complete. Start a new one to continue.",
  "جلسة المحاكاة غير موجودة أو انتهت.": "Simulation session is missing or expired.",
  "التسجيل المحدد غير موجود.": "Recording not found.",
  "بيانات المشروع غير جاهزة بعد.": "Project catalog is not ready yet.",
  "ميزة إعادة تشغيل التسجيل غير متاحة.": "Recorded replay unavailable.",
  "لا يتوفر للوكيل بصمة كاملة لهوية الشيفرة؛ إعادة التشغيل هذه تعليمية وليست نتيجة تقييم مسجلة.": "Agent lacks a complete code fingerprint; this replay is educational, not a scored evaluation.",
  "يشمل فاصل الثقة المقترن للصعود الصفر؛ لذا فالنتيجة غير حاسمة، ولا تثبت غياب الأثر.": "The paired climb confidence interval includes zero; inconclusive does not prove no effect.",
  "ملفات الوكلاء المطلعة والعمياء أوزان مُصدّرة للسياسة، وليست ملفات final.zip نفسها التي خضعت للتقييم المسجل.": "Sighted and blind actor files are exported policy weights, not the exact scored final.zip artifacts.",
  "يسجل إعداد التدريب بصمة البيانات ولا يتضمن plant_sha؛ لذلك فإعادة تشغيل الوكيل غير موثقة.": "Training config records a data fingerprint but no plant_sha; actor replays are unverified.",
  "يعتمد معظم التفوق الظاهر للوكلاء المدرّبين على السياسات المكتوبة يدويًا على نموذج طرق غير متحقق منه.": "Most apparent trained-agent advantage over manual policies depends on the unvalidated knock model.",
  "تُحاكى عقدة التوربين بثوابت مفترضة ولا يقابلها حساس في السيارة.": "Turbine node uses assumed constants and has no matching car sensor.",
  "يتذبذب تحديث الكتلة وسائل التبريد عند dt=1 s؛ لذلك لا يصح الاستشهاد بنتائج مسح H/τ حاليًا.": "Block/coolant update oscillates at dt=1 s; H/τ sweep claims remain unquotable.",
  "قيمة الضرر المتكاملة مؤشر تقريبي وليست تنبؤًا بالعمر الفعلي للمكونات.": "Integrated damage is a proxy, not a prediction of actual component life.",
  "تحذير من النموذج؛ افتح المصدر للاطلاع على التفاصيل.": "Model warning; open source for details.",
  "أعاد نموذج المحرك قيَمًا غير منتهية في بعض المخرجات؛ راجع نقطة التشغيل أو المصدر.": "The engine model returned non-finite diagnostics; review the operating point or source.",
  "تنبيه علمي: راجع المصدر والتفاصيل قبل تفسير هذه النتيجة.": "Scientific caution: review source and details before interpreting this result.",
  "تعذّر إكمال الطلب. حاول مرة أخرى.": "Could not complete the request. Try again.",
  "أحد مدخلات التحكم غير مدعوم.": "A control input is unsupported.",
  "قيمة أحد المدخلات غير صالحة أو خارج الحدود.": "An input is invalid or outside bounds.",
  "قيم المشغلات تتجاوز حدودها الفيزيائية.": "Actuator values exceed physical bounds.",
  "تعذّر تحميل هذا الوكيل أو لم تتطابق بياناته مع نسخة المشروع الحالية.": "Could not load this actor or its data does not match the current project version.",
  "تعذّر الاتصال بالمحاكاة. تحقّق من تشغيل الخدمة المحلية.": "Could not connect to simulation. Check that the local service is running.",
  "لا يسمح بعرض هذا المصدر.": "This source cannot be displayed.",
  "سرعة المركبة": "Vehicle speed",
  "درجة حرارة الجو": "Ambient temperature",
  "تعديل توقيت الشرارة": "Spark trim",
  "تعديل لامدا": "Lambda trim",
  "تعديل ضغط المانيفولد": "MAP trim",
  "سرعة مروحة الرديتر": "Radiator fan duty",
  "سرعة مضخة التبريد": "Coolant pump duty",
  "تدخل الشحنة عبر صمام السحب وينزل المكبس.": "Charge enters through intake valve and piston descends.",
  "يصعد المكبس ويضغط الشحنة المحبوسة.": "Piston rises and compresses trapped charge.",
  "الشرارة تسبق الاحتراق؛ الغازات تدفع المكبس إلى الأسفل.": "Spark precedes combustion; gas pushes the piston downward.",
  "يصعد المكبس وتخرج الغازات عبر صمام العادم.": "Piston rises and gas leaves through exhaust valve.",
  "أمر مروحة الرديتر": "Radiator fan command",
  "أمر مضخة التبريد": "Coolant pump command",
  "معدن المحرك": "Engine metal",
  "مرجع ECU / حلقة المرجع": "ECU reference / reference loop",
  "بعد حد التغيير": "After slew limit",
  "القيمة النهائية من المصدر": "Final value from source",
  "السياسة الحالية تحدد الأوامر. المسودة اليدوية محفوظة وغير مستخدمة أثناء التشغيل الآلي.": "Current policy sets commands. Manual draft is preserved and unused during automatic operation.",
  "الكتلة وسائل التبريد": "Block and coolant",
  "طاقة الوقود": "Fuel energy",
  "احتكاك ودوران الزيت": "Oil friction and rotation",
  "حد الغاز": "Gas boundary",
  "الرديتر": "Radiator"
});
const reverse = new Map(Object.entries(UI_COPY).map(([ar,en])=>[en,ar]));
export function uiText(value, language) {
  if (typeof value !== "string") return value;
  const key = value.trim().replace(/\s+/g," ");
  const translated = language === "en" ? UI_COPY[key] : reverse.get(key);
  if (translated === undefined) return value;
  return value.match(/^\s*/)[0] + translated + value.match(/\s*$/)[0];
}
export function templateText(ar, en, language, values) {
  return (language === "en" ? en : ar).replace(/\{(\d+)\}/g, (_,index)=>String(uiText(values[Number(index)],language)));
}
