"""show_record.py -- one recorded episode, drawn and tabulated: what the road
asked, what the agent saw and did, what the engine and the heat did, against
the baseline ECU driving the same road beside it.

    python show_record.py results/records/conditions/1_25_C/sighted_seed0.npz
    python show_record.py results/records/conditions/1_25_C/sighted_seed0.npz --episode 2
    python show_record.py results/agents/terrain_dt1/blind_seed6/eval_record.npz --episode 4
    python show_record.py runs/terrain_dt1/sighted_seed0/train_record.npz --episode 54
    python show_record.py <record> --list          the episodes a record holds
    python show_record.py <record> --table 60      a row every 60 s instead of the figure
    python show_record.py "results/records/conditions/*/baseline_ECU.npz" --zigzag
                                                    the coolant node's step-to-step swing (a glob)

Reads any record written with step_record.py's fields: the conditions test
and the knock margin (results/records/), the twenty frozen episodes
(eval_record.npz) and training (train_record.npz, one episode at a time by its
`episode` number). Records written before 7 October 2026 lack the road speed,
the gear and the baseline car; their panels say so instead of guessing.

Writes the figure beside the record (<record>.ep<N>.png) unless --out is given.
Monitoring and understanding only: it computes nothing that is quoted.
"""
import argparse
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

TRIGGER_C = 850.0
ACTS = (("spark trim", "deg"), ("lambda trim", ""), ("boost trim", "kPa"), ("fan duty", ""), ("pump duty", ""))
AGENT, BASE, ASKED, LIMIT = "#2a78d6", "#8a9096", "#9cc3ef", "#d03b3b"


def load(path, episode):
    """One episode's arrays, time first, from either layout: stacked (episode,
    step, ...) or flat with an `episode` column (training)."""
    r = dict(np.load(path))
    meta = {}
    side = os.path.splitext(path)[0] + ".json"
    if os.path.isfile(side):
        with open(side, encoding="utf-8") as fh:
            meta = json.load(fh)
    if "episode" in r and r["reward"].ndim == 1:                 # training: flat
        eps = np.unique(r["episode"])
        if episode not in eps:
            raise SystemExit(f"episode {episode} is not in this record ({eps.min()}-{eps.max()})")
        m = r["episode"] == episode
        out = {k: v[m] for k, v in r.items() if v.shape[:1] == m.shape}
        if "weights" in out and out["weights"].ndim == 2:
            meta["weights"] = out["weights"][0].tolist()
        roads = os.path.join(os.path.dirname(path), "train_roads.npz")
        if "grade" not in out and os.path.isfile(roads):
            # a record from before 7 October: the road regenerated from the
            # run's seed and checked against its torque request (training_roads.py)
            rd = dict(np.load(roads))
            for k in ("grade", "v_kmh", "rpm", "gear", "applied", "weights"):
                if k in rd:
                    out[k] = rd[k][m]
            if "weights" in out:
                meta["weights"] = out["weights"][0].tolist()
            meta["road"] = f"{rd['family'][episode]} road, regenerated by training_roads.py"
        return out, dict(meta, kind="training", n_episodes=len(eps))
    n = r["reward"].shape[0]
    if not 0 <= episode < n:
        raise SystemExit(f"episode {episode} is not in this record (0-{n - 1})")
    steps = int(r["steps"][episode]) if "steps" in r else r["reward"].shape[1]
    out = {k: v[episode][:steps] for k, v in r.items()
           if v.ndim >= 2 and v.shape[0] == n and k not in ("weights",)}
    if "weights" in r:
        meta["weights"] = np.asarray(r["weights"][episode]).tolist()
    if "episode_seed" in r:
        meta["seed"] = int(r["episode_seed"][episode])
    return out, dict(meta, kind="evaluation", n_episodes=n)


def list_episodes(path):
    r = dict(np.load(path))
    if "episode" in r and r["reward"].ndim == 1:
        eps, idx, counts = np.unique(r["episode"], return_index=True, return_counts=True)
        print(f"{path}: training record, {len(eps)} episodes, {len(r['reward'])} steps")
        for e, i, c in zip(eps, idx, counts):
            m = r["episode"] == e
            g = r["grade"][m] if "grade" in r else None
            road = f"grade max {100 * np.nanmax(g):5.1f} %" if g is not None else "road not recorded"
            print(f"  episode {e:4d}: {c:4d} steps, return {float(np.sum(r['reward'][m])):8.2f}, {road}")
        return
    n = r["reward"].shape[0]
    print(f"{path}: {n} episodes x {r['reward'].shape[1]} steps, {len(r)} fields")
    for i in range(n):
        seed = int(r["episode_seed"][i]) if "episode_seed" in r else None
        w = np.round(r["weights"][i], 3).tolist() if "weights" in r else None
        dmg = float(r["damage_cum"][i][-1]) if "damage_cum" in r else float(np.nansum(r["damage_rate"][i]))
        print(f"  {i:2d}: seed {seed}, weights {w}, return {float(np.nansum(r['reward'][i])):8.2f}, "
              f"damage {dmg:8.1f}, peak turbine {float(np.nanmax(r['t_turb'][i])) - 273.15:6.1f} C")


def zigzag(paths, after_s=200):
    """The coolant node's step-to-step swing after `after_s` (on the climb):
    the median and 95th percentile of |change| per step, the share of steps
    that reverse direction, and the fan and pump the policy ran. A swing that
    reverses on nearly every step is the explicit integrator's stiffness, not
    physics (agreed fix 1 of 30 September: sub-step the thermal network). The
    coolant is input 6 of 23 and the charge temperature made from it input 9,
    so the agents see it."""
    import glob as _glob
    print(f"{'record':58s} {'|dT| med K':>10s} {'p95 K':>6s} {'reverses':>8s} {'fan':>5s} {'pump':>5s}")
    for p in sorted(q for pat in paths for q in _glob.glob(pat)):
        r = np.load(p)
        tb = np.asarray(r["t_block"], float)
        if tb.ndim == 1:
            tb = tb[None, :]
        tb = tb[:, after_s:]
        d = np.diff(tb, axis=1)
        med = float(np.median(np.nanmedian(np.abs(d), axis=1)))
        p95 = float(np.median(np.nanpercentile(np.abs(d), 95, axis=1)))
        rev = float(np.median(np.mean(np.sign(d[:, 1:]) != np.sign(d[:, :-1]), axis=1)))
        ap = np.asarray(r["applied"], float)
        ap = ap[None] if ap.ndim == 2 else ap
        name = os.path.relpath(p).replace(os.sep, "/")
        print(f"{name[-58:]:58s} {med:10.2f} {p95:6.2f} {rev:8.2f} {np.median(ap[:, after_s:, 3]):5.2f} "
              f"{np.median(ap[:, after_s:, 4]):5.2f}")


def physical(a):
    """The policy's [-1, 1] command as the actuator value it asks for."""
    from engine_env import ACT_LO, ACT_HI
    return ACT_LO + (np.clip(a, -1.0, 1.0) + 1.0) * 0.5 * (ACT_HI - ACT_LO)


def table(rec, every):
    t = np.arange(len(rec["reward"]))
    has = lambda k: k in rec
    print(f"{'t s':>5s} {'grade%':>6s} {'km/h':>5s} {'gear':>4s} {'rpm':>5s} {'MAP':>6s} {'MAPb':>6s} "
          f"{'Treq':>5s} {'T':>5s} {'spark':>6s} {'lam':>6s} {'boost':>6s} {'fan':>4s} {'pump':>4s} "
          f"{'turb C':>6s} {'base C':>6s} {'oil C':>5s} {'KI':>5s} {'dmg':>7s} {'dmg b':>7s}")
    for k in t[::every]:
        ap = rec["applied"][k]
        cell = lambda key, f, off=0.0: (f % (float(rec[key][k]) - off)) if has(key) else " " * len(f % 0)
        print(f"{k:5d} {100 * rec['grade'][k]:6.2f} {cell('v_kmh', '%5.0f')} {cell('gear', '%4.0f')} "
              f"{rec['rpm'][k]:5.0f} {rec['map_kpa'][k]:6.1f} {cell('map_kpa_base', '%6.1f')} "
              f"{rec['torque_req'][k]:5.0f} {rec['torque'][k]:5.0f} {ap[0]:+6.2f} {ap[1]:+6.3f} {ap[2]:+6.1f} "
              f"{ap[3]:4.2f} {ap[4]:4.2f} {rec['t_turb'][k] - 273.15:6.1f} "
              f"{cell('t_turb_base', '%6.1f', 273.15)} {rec['t_oil'][k] - 273.15:5.1f} {rec['ki'][k]:5.2f} "
              f"{cell('damage_cum', '%7.1f')} {cell('damage_base_cum', '%7.1f')}")


def figure(rec, meta, title, out):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    t = np.arange(len(rec["reward"])) * float(meta.get("dt", 1.0))
    fig, ax = plt.subplots(8, 2, figsize=(14, 19), sharex=True)

    def panel(a, label, unit=""):
        a.set_title(label + (f", {unit}" if unit else ""), fontsize=9, loc="left")
        a.grid(alpha=0.25, lw=0.5)
        a.tick_params(labelsize=8)

    def missing(a, label):
        panel(a, label)
        a.text(0.5, 0.5, "not in this record (written before 7 October 2026)", ha="center", va="center",
               transform=a.transAxes, fontsize=8, color=BASE)

    # left: the road and the engine
    a = ax[0, 0]
    if "v_kmh" in rec:
        panel(a, "road speed", "km/h")
        a.plot(t, rec["v_kmh"], color=AGENT, lw=1.4)
    else:
        missing(a, "road speed")
    a = ax[1, 0]
    if "grade" in rec:
        panel(a, "grade", "%")
        a.plot(t, 100 * rec["grade"], color=AGENT, lw=1.4)
    else:
        missing(a, "grade")
    a = ax[2, 0]
    if "gear" in rec:
        panel(a, "gear (from engine and road speed)")
        a.step(t, rec["gear"], where="post", color=AGENT, lw=1.4)
        a.set_ylim(0, 8.8)
    else:
        missing(a, "gear")
    a = ax[3, 0]
    if "rpm" in rec:
        panel(a, "engine speed", "rpm")
        a.plot(t, rec["rpm"], color=AGENT, lw=1.4)
    else:
        missing(a, "engine speed")
    a = ax[4, 0]
    if "map_kpa" in rec:
        panel(a, "manifold pressure", "kPa")
        if "map_kpa_base" in rec:
            a.plot(t, rec["map_kpa_base"], color=BASE, lw=1.2, label="baseline ECU")
        a.plot(t, rec["map_kpa"], color=AGENT, lw=1.4, label="this policy")
        a.legend(fontsize=7, loc="upper left")
    else:
        missing(a, "manifold pressure")
    a = ax[5, 0]
    panel(a, "torque", "Nm")
    a.plot(t, rec["torque_req"], color=BASE, lw=1.2, label="asked for")
    a.plot(t, rec["torque"], color=AGENT, lw=1.4, label="delivered")
    short = rec["torque"] < 0.95 * rec["torque_req"]
    if short.any():
        a.scatter(t[short], rec["torque"][short], s=6, color=LIMIT, zorder=3,
                  label=f"under 95 % ({int(short.sum())} steps)")
    a.legend(fontsize=7, loc="upper left")
    a = ax[6, 0]
    panel(a, "knock integral (model, untested against the car)")
    a.plot(t, rec["ki"], color=AGENT, lw=1.2)
    a.axhline(0.85, color=LIMIT, ls=":", lw=1, label="0.85, the damage knee")
    a.legend(fontsize=7, loc="upper left")
    a = ax[7, 0]
    panel(a, "reward terms (fuel, life, response)")
    for k, c in (("r_fuel", "#1baf7a"), ("r_life", AGENT), ("r_resp", "#e87ba4")):
        a.plot(t, rec[k], lw=1.0, color=c, label=k)
    a.legend(fontsize=7, loc="lower left", ncol=3)
    a.set_xlabel("time, s", fontsize=9)

    # right: what the agent did, and what it cost
    asked = physical(rec["action"])
    for j, (name, unit) in enumerate(ACTS[:3]):
        a = ax[j, 1]
        panel(a, name, unit)
        a.plot(t, asked[:, j], color=ASKED, lw=1.0, label="asked (the network's command)")
        if "applied" in rec:
            a.plot(t, rec["applied"][:, j], color=AGENT, lw=1.4, label="applied (after slew and bounds)")
        a.axhline(0.0, color=BASE, lw=0.8)
        if j == 0:
            a.legend(fontsize=7, loc="lower left")
    a = ax[3, 1]
    src = rec["applied"] if "applied" in rec else asked
    panel(a, "fan and pump duty, " + ("applied" if "applied" in rec else "asked (applied not recorded)"))
    a.plot(t, src[:, 3], color=AGENT, lw=1.4, label="fan")
    a.plot(t, src[:, 4], color="#1baf7a", lw=1.4, label="pump")
    a.set_ylim(-0.05, 1.05)
    a.legend(fontsize=7, loc="lower left")
    a = ax[4, 1]
    panel(a, "turbine housing", "C")
    if "t_turb_base" in rec:
        a.plot(t, rec["t_turb_base"] - 273.15, color=BASE, lw=1.2, label="baseline ECU")
    a.plot(t, rec["t_turb"] - 273.15, color=AGENT, lw=1.4, label="this policy")
    a.axhline(TRIGGER_C, color=LIMIT, ls=":", lw=1, label="850 C trigger")
    a.legend(fontsize=7, loc="upper left")
    a = ax[5, 1]
    panel(a, "oil and coolant", "C")
    a.plot(t, rec["t_oil"] - 273.15, color=AGENT, lw=1.4, label="oil")
    a.plot(t, rec["t_block"] - 273.15, color="#1baf7a", lw=1.4, label="coolant (block)")
    if "t_oil_base" in rec:
        a.plot(t, rec["t_oil_base"] - 273.15, color=BASE, lw=1.0, ls="--", label="oil, baseline")
    a.legend(fontsize=7, loc="upper left")
    a = ax[6, 1]
    panel(a, "damage, cumulative (relative units)")
    if "damage_cum" in rec:
        a.plot(t, rec["damage_base_cum"], color=BASE, lw=1.2, label=f"baseline {rec['damage_base_cum'][-1]:.0f}")
        a.plot(t, rec["damage_cum"], color=AGENT, lw=1.4, label=f"this policy {rec['damage_cum'][-1]:.0f}")
    elif "damage_rate" in rec:
        dmg = np.nancumsum(rec["damage_rate"]) * float(meta.get("dt", 1.0))
        a.plot(t, dmg, color=AGENT, lw=1.4, label=f"this policy {dmg[-1]:.0f}")
    else:
        from engine_env import damage_rate
        rate = np.array([damage_rate(tt, oo, kk) for tt, oo, kk in zip(rec["t_turb"], rec["t_oil"], rec["ki"])])
        dmg = np.cumsum(rate) * float(meta.get("dt", 1.0))
        a.plot(t, dmg, color=AGENT, lw=1.4, label=f"this policy {dmg[-1]:.0f} (from the recorded heat)")
    a.legend(fontsize=7, loc="upper left")
    a = ax[7, 1]
    panel(a, "reward per step")
    a.plot(t, rec["reward"], color=AGENT, lw=1.0)
    a.set_xlabel("time, s", fontsize=9)
    fig.suptitle(title, fontsize=10, x=0.01, ha="left")
    fig.tight_layout(rect=(0, 0, 1, 0.985))
    fig.savefig(out, dpi=110)
    print(f"wrote {out}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("record")
    ap.add_argument("--episode", type=int, default=0)
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--table", type=int, default=None, metavar="SECONDS")
    ap.add_argument("--out", default=None)
    ap.add_argument("--zigzag", action="store_true",
                    help="the coolant node's step-to-step swing on the climb, for every record matched")
    a = ap.parse_args()
    if a.zigzag:
        return zigzag([a.record])
    if a.list:
        return list_episodes(a.record)
    rec, meta = load(a.record, a.episode)
    head = [meta.get("policy") or os.path.basename(os.path.dirname(a.record)),
            meta.get("condition"), f"grade {100 * meta['grade']:.2f} %" if meta.get("grade") else None,
            f"episode {a.episode} of {meta['n_episodes']}", f"seed {meta['seed']}" if "seed" in meta else None,
            "weights " + "/".join(f"{w:.2f}" for w in meta["weights"]) if "weights" in meta else None,
            meta.get("road")]
    title = "   ".join(h for h in head if h)
    print(title)
    if a.table:
        return table(rec, a.table)
    out = a.out or f"{os.path.splitext(a.record)[0]}.ep{a.episode}.png"
    figure(rec, meta, title, out)


if __name__ == "__main__":
    main()
