import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { PreferencesProvider } from './Preferences';
import './style.css';
import './arabic.css';
import './studio.css';
import './theme.css';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import '@fontsource/dm-sans/700.css';
import '@fontsource/ibm-plex-mono/400.css';
import '@fontsource/ibm-plex-mono/500.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<PreferencesProvider><App /></PreferencesProvider>);
